### PR TITLE
AC-522: Prevented crashing when selecting "Take a photo" option

### PR DESCRIPTION
**Pull request by sp2710**
## Description of what I changed
Some minor changes to prevent crashing of app

## Issue I worked on
JIRA Issue: https://issues.openmrs.org/browse/AC-522

Before
ezgif com-video-to-gif

Now
ezgif com-video-to-gif

## Checklist: I completed these to help reviewers :)
- [x] My pull request only contains **ONE single commit**
- [ ] I have **added tests** to cover my changes. (If you refactored
existing code that was well tested you do not have to add tests)
- [ ] All new and existing **tests passed**.
- [x] My pull request is **based on the latest changes** of the master branch.

### CODE REVIEW

**Comment by f4ww4z** [comment]
@sp2710  See my comment at https://issues.openmrs.org/browse/AC-552 .

**Comment by codepoet2017390** [comment]
@sp2710 Can u please add Gifs showing that there issue is completely resolved.

**Comment by sp2710** [comment]
@codepoet2017390 I have added the Gifs

**Comment by codepoet2017390** [comment]
@sp2710 please click a picture and see if it gets loaded into the imageView.

**Comment by sp2710** [comment]
@codepoet2017390 It is working perfectly.
I have updated the Gifs

**Comment by codepoet2017390** [comment]
Well done @sp2710. I was unable to resolve the issue but you did it with a few lines of code.

**Comment by f4ww4z** [comment]
@sp2710 Change the **issue link** and **PR title** to AC-522. AC-552 is a duplicate of it. @codepoet2017390 Is it ok if I reassign this issue to @sp2710 ? This change is properly formatted and working correctly.

**Comment by sp2710** [comment]
@f4ww4z I have updated the PR.

**Pull request merged**
