### PR TITLE
AC-832 Migrating type converter package to kotlin and fixing minor issue with type converters

### PR DESCRIPTION
**Pull request by LuGO0**
## Description of what I changed
1. Fixed some irregularities in type converters
2. Deleted one redundant type converter
3. Converting the package to kotlin

## Issue I worked on

JIRA Issue: https://issues.openmrs.org/browse/AC-832

## Checklist: I completed these to help reviewers :)

- [ ] My pull request only contains **ONE single commit**
(the number above, next to the 'Commits' tab is 1).

- [ ] I have **added tests** to cover my changes. (If you refactored
existing code that was well tested you do not have to add tests)

- [x] All new and existing **tests passed**.

- [x] My pull request is **based on the latest changes** of the master branch.

### CODE REVIEW

**Comment by LuGO0** [comment]
@f4ww4z @rishabh-997 please check up the changes once before I convert them into kotlin!!

**Review by rishabh-997 — COMMENTED** [review]
Changes are fine, you can migrate them to kotlin :+1:

**Comment by LuGO0** [comment]
@rishabh-997 i will convert them into kotlin soon just caught up in some work, will make the PR ready for review then 👍

**Review by rishabh-997 — COMMENTED** [review]
Nice work @LuGO0, can you try to fix the Travis failure...

**Comment by LuGO0** [comment]
@rishabh-997 I think its not a travis failure but  actually travis failed to start test can you restart the travis test for this commit !!

**Comment by LuGO0** [comment]
@rishabh-997 I rebased its fine now :)

**Comment by LuGO0** [comment]
@rishabh I encountered No NPEs while normal usage.

**Pull request merged**
