### PR TITLE
AC-479 Refactored the code with all the subtasks in it

### PR DESCRIPTION
**Pull request by rishabh-997**
## Description of what I changed
I worked on the following issues since many of them were one-liner so I created a single PR:
1. obsolete SDK_INT check [link](https://issues.openmrs.org/browse/AC-587)
2. removed unused imports [link](https://issues.openmrs.org/browse/AC-598)
3. annotate @notnull where necessary [link](https://issues.openmrs.org/browse/AC-564)
4. use the lambda function [link](https://issues.openmrs.org/browse/AC-565)
5. convert explicit types to <> [link](https://issues.openmrs.org/browse/AC-566)
6. removed redundant typecast [link](https://issues.openmrs.org/browse/AC-599)
7. use start/end attributes instead of left/right attributes [link](https://issues.openmrs.org/browse/AC-597)

## Issue I worked on

JIRA Issue: https://issues.openmrs.org/browse/AC-479

## Checklist: I completed these to help reviewers :)

- [ ] My pull request only contains **ONE single commit**
(the number above, next to the 'Commits' tab is 1).

- [ ] I have **added tests** to cover my changes. (If you refactored
existing code that was well tested you do not have to add tests)

- [x] All new and existing **tests passed**.

- [x] My pull request is **based on the latest changes** of the master branch.

### CODE REVIEW

**Comment by rishabh-997** [comment]
@f4ww4z sir, what about instead of creating 7 different PR's for all those sub-issues, you merge 7 commits into the code???

**Comment by Devanshk9** [comment]
hi @rishabh-997 please merge the 8 commits into one so that your workspace looks clean

**Comment by rishabh-997** [comment]
> Hi @rishabh-997.
> You have to follow the [PR guidelines](https://wiki.openmrs.org/display/docs/Pull+Request+Tips).
> It appears that the some of the issues are closed. You can only make PR for issues that are **Ready For Work**.
> 
> The work flow is like this:
> When you observe an error in the app, the first step is to see if it has already been fixed. You can see that by checking if there already exists a JIRA issue for that, if the status of the issue is closed, that means it has been fixed, if it is ready for work, you can claim the issue and then start working on it.
> If the issue is not there, you can go ahead and create the issue. But, before you start working on the issue, please wait until someone reviews the issue and marks it RFW.

see my first comment, the ticket of main title is ready for work, i just refactored few more warnings... I have no issue opening all those closed PR and sending 8 different PRs but 4-5 linrs of changes for every PR is unecessary... Thats why i am waiting for @f4ww4z sir reply, will close this and send 8 PR if he says so 🤘

**Comment by f4ww4z** [comment]
@rishabh-997 You should just do what's described in [AC-564](https://issues.openmrs.org/browse/AC-564), since it's quite hard to review in 1 PR. Also see the merge conflict. Create a PR for each subtask.

**Comment by rishabh-997** [comment]
> @rishabh-997 You should just do what's described in [AC-564](https://issues.openmrs.org/browse/AC-564), since it's quite hard to review in 1 PR. Also see the merge conflict. Create a PR for each subtask.

Ok sir... closing this PR and sending individual PR...

**Pull request closed without merging**
