### PR TITLE
Ignore to check if country code picker is not empty

### PR DESCRIPTION
**Pull request by rupesh-kumar-lpu**
Better not to include line to check if the country code is not empty, As it always returning True value which make the whole method 'areFieldsNotEmpty()' to return true, By which it is always showing Dialogue box saying "All patient information entered will be lost", even if all the fields are empty. This might be due to default value of county box picker is selected.

## Issue I worked on

JIRA Issue: https://issues.openmrs.org/browse/AC-

## Checklist: I completed these to help reviewers :)

- [x] My pull request only contains **ONE single commit**
(the number above, next to the 'Commits' tab is 1).

- [ ] I have **added tests** to cover my changes. (If you refactored
existing code that was well tested you do not have to add tests)

- [x] All new and existing **tests passed**.

- [x] My pull request is **based on the latest changes** of the master branch.

### CODE REVIEW

**Comment by rupesh-kumar-lpu** [comment]
@f4ww4z I am unable to login to openmrs issues. It keeps on asking wrong username or password. Where as I have reset password about 4 times

**Comment by rupesh-kumar-lpu** [comment]
I am not able to apply jira ticket issue

**Comment by Abdelaty** [comment]
hey @rupesh-kumar-lpu I think you can create a ticket [here](http://om.rs/helpdesk), to fix your account problem.

**Comment by rishabh-997** [comment]
> @f4ww4z I am unable to login to openmrs issues. It keeps on asking wrong username or password. Where as I have reset password about 4 times

post this issue on jira page, i faced the same problem in the beginning and it was resolved then.

**Comment by rishabh-997** [comment]
> I am not able to apply jira ticket issue

Dont create any pull requests before having a ticket which is labelled as **ready for work**

**Comment by rupesh-kumar-lpu** [comment]
Thanks @rishabh-997 and @Abdelaty I hope my issue of login will be resolved after posting issue on jira page. Posting on jira page you mean here openmrs talks page(I am able to login over threre). Actually I am not able to login here even https://openmrs.atlassian.net/servicedesk/customer/user/login?destination=portals

**Comment by Abdelaty** [comment]
@rupesh-kumar-lpu You can try to create a new account and user id. Hope it solved as soon as possible and you be able to contribute.

**Comment by tbagz104** [comment]
@rupesh-kumar-lpu I have already raised an [issue](https://issues.openmrs.org/browse/AC-715) which **solves this**. Please check the issues before making the PR :)

**Comment by rupesh-kumar-lpu** [comment]
@tbagz104  Oops! I got it how it works Thanks

**Comment by rupesh-kumar-lpu** [comment]
@Abdelaty I have created another account but same facing same problem. I have created ticked where you told me earlier. Hope I will be able to login in issue section soon. Thanks for the help.

**Comment by rupesh-kumar-lpu** [comment]
@rishabh-997 got it thanks

**Comment by AryanGanotra07** [comment]
Hi @rupesh-kumar-lpu , You will be able to sign in soon, I was having this problem for sometime too. And related to the pull requests, please keep these points in mind. 
1. Issue ticket shouldn't be already there in the issue tracker.
2. Make pull request only when mentor makes it ready for work.
3.  Maintain the format of pull request. 

Thanks.

**Comment by f4ww4z** [comment]
@rupesh-kumar-lpu Any updates on this? What JIRA issue is this?

**Comment by f4ww4z** [comment]
Closing due to the issue not being filed on JIRA. @rupesh-kumar-lpu Reopen once you pinged me in the issue page.

**Pull request closed without merging**
