### PR TITLE
AC-225 and AC-226

### PR DESCRIPTION
**Pull request by shivtej1505**

### CODE REVIEW

**Comment by AdamGrzybkowski** [comment]
@shivtej1505 thanks for your PR. I have few recommendations. First it would be great if you could use JIRA so nobody will work on the same ticket as you. Next it will be better if you create separate PR for each ticket.

**Comment by AdamGrzybkowski** [comment]
@shivtej1505 I will merge this PR but please consider my points above next time :)

**Comment by AdamGrzybkowski** [comment]
@shivtej1505 I see now you claimed those tickets. I thought you didn't because I didn't see any claimed tickets in AC sprint, but I found that I don't see those tickets at all. I can open them only by direct link. That's strange...

**Comment by AdamGrzybkowski** [comment]
@rkorytkowski Could you add Code review column to the JIRA board  ?

**Comment by shivtej1505** [comment]
@AdamGrzybkowski, no problem. I have used JIRA before, it is quite strange that the JIRA isn't showing claimed tickets. BTW, thanks! :)

**Review by MrKrishnaAgarwal — COMMENTED** [review]
Hello 👋🏻

**Pull request merged**
