### PR TITLE
AC-402:Implement the Provider Module

### PR DESCRIPTION
**Pull request by csmuthukuda**
Hi
This is an Initial Commit.
This is not a complete PR.I will keep update my progress in here by updating this PR

Issue Link : https://issues.openmrs.org/browse/AC-402

### CODE REVIEW

**Comment by dkayiwa** [comment]
Did you take a look at the codacay-bot review comments?

**Comment by dkayiwa** [comment]
@csmuthukuda can you take a look at these merge conflicts and comments above?

**Comment by csmuthukuda** [comment]
@dkayiwa  I'm still working on this feature while doing other features too. I have made a PR just to show my mentor to review the things. I'll let you know after this has been completed :)

**Comment by dkayiwa** [comment]
@csmuthukuda what is the state of this?

**Comment by dkayiwa** [comment]
@csmuthukuda feel free to reclaim this when you get the time.

**Pull request closed without merging**
