### PR TITLE
AC-635:Unit Test Error Fix

### PR DESCRIPTION
**Pull request by ishaan-das**
## Description of what I changed

What I was previously doing was creating a new Cache.java file to fix the deprecated library LruCache error. But that fix wasn't the right way to do as it was generating some errors in travis CL. So, I implemented a new approach. I added the activeandroid library as a module dependency rather than an external dependency. Then, I edited the Cache.java file inside the activeandroid module and that seems to have fixed the issue.

## Issue I worked on

JIRA Issue: https://issues.openmrs.org/browse/AC-635

## Checklist: I completed these to help reviewers :)

- [x] My pull request only contains **ONE single commit**
(the number above, next to the 'Commits' tab is 1).

- [ ] I have **added tests** to cover my changes. (If you refactored
existing code that was well tested you do not have to add tests)

- [ ] All new and existing **tests passed**.

- [x] My pull request is **based on the latest changes** of the master branch.

### CODE REVIEW

**Comment by ishaan-das** [comment]
please review @f4ww4z

**Comment by rishabh-997** [comment]
20/24 of your test are still failing because of initialization error, try to run presenter test locally before committing

**Comment by ishaan-das** [comment]
But that error is not related to cache.java or lrucache.java. it's something else.

**Comment by f4ww4z** [comment]
@ishaan-das  you've basically copied the idea from #637 . Closing this to focus on that PR instead.

**Comment by ishaan-das** [comment]
@f4ww4z No, I haven't copied anything. I didn't even see rishabh's pull request until now. I don't know why our implementation method happened to be the same.

**Pull request closed without merging**
