### PR TITLE
Fixed App crashes on accessing patient dashboard

### PR DESCRIPTION
**Pull request by MasterBlaster99**
### Description of what i have changed 
i have fixed the problem of  app gets crashed when we click on the create patient dashboard 
issue #AC-772 . now the activity for creating patient opens without any error
regpateint

### CODE REVIEW

**Comment by HerbertYiga** [comment]
cc @f4ww4z

**Comment by LuGO0** [comment]
@MasterBlaster99 get it assigned to you then make a PR. also have you tested the changes on lower API devices?

**Comment by MasterBlaster99** [comment]
> @MasterBlaster99 get it assigned to you then make a PR. also have you tested

**Comment by MasterBlaster99** [comment]
> @MasterBlaster99 get it assigned to you then make a PR. also have you tested the changes on lower API devices?

Yes Sir, I have also tested it on lower API devices 
but i don,t know how to get an issue assigned to me. there is no claim issue button on Open Mrs Jira Issues Section.
please help me with this

**Pull request closed without merging**
