### PR TITLE
AC-478 Encrypt database with SQLCipher library

### PR DESCRIPTION
**Pull request by rishabh-997**
## Description of what I changed
The` cwac-saferoom` library is now deprecated and hasn't been into development lately as the sql-cipher:4.4.0 provides support for the room encryption, so I read about it and tried implementing it

## Issue I worked on

JIRA Issue: https://issues.openmrs.org/browse/AC-478

## Checklist: I completed these to help reviewers :)

- [x] My pull request only contains **ONE single commit**
(the number above, next to the 'Commits' tab is 1).

- [ ] I have **added tests** to cover my changes. (If you refactored
existing code that was well tested you do not have to add tests)

- [x] All new and existing **tests passed**.

- [x] My pull request is **based on the latest changes** of the master branch.

### CODE REVIEW

**Comment by rishabh-997** [comment]
Here is the link to implementation:
https://github.com/sqlcipher/android-database-sqlcipher#using-sqlcipher-for-android-with-room
After accessing the provider dashboard, the previous database still gets corrupted which I am not getting why. Is there any way to check if the provider database is getting encrypted or not.

**Comment by LuGO0** [comment]
@rishabh-997 there is a lot of confusion regarding which model are being used and which arent I faced this while working on the provider module. maybe the problem might be there I will read it and then say !!

**Comment by LuGO0** [comment]
@rishabh-997 maybe its because we arent using  all the annotated entities in the AppDatabase.java # like , the PatientEntity we arent using that.
Thats why I think we will first have to migrate completely from tables to room entities and then implement sqlCipher

**Comment by f4ww4z** [comment]
>  After accessing the provider dashboard, the previous database still gets corrupted which I am not getting why. Is there any way to check if the provider database is getting encrypted or not.

Since the app is still using the activeandroid library for local database (and not using Room), we cannot check for that yet. We have to migrate all entities to the respective Room classes, e.g. `Person` to `PersonEntity`. I think this PR will be open until all migrations are complete, like discussed in the JIRA issue.

**Comment by rishabh-997** [comment]
> > After accessing the provider dashboard, the previous database still gets corrupted which I am not getting why. Is there any way to check if the provider database is getting encrypted or not.
> 
> Since the app is still using the activeandroid library for local database (and not using Room), we cannot check for that yet. We have to migrate all entities to the respective Room classes, e.g. `Person` to `PersonEntity`. I think this PR will be open until all migrations are complete, like discussed in the JIRA issue.

Can you create a sample issue as subtask in jira explaining how exactly I need to change person to person entity... I will add others afterwards...

**Comment by f4ww4z** [comment]
@rishabh-997 How is your progress for this?

**Comment by rishabh-997** [comment]
> How is your progress for this

I will need to do some research on encrypting the existing database also using SQLCipher+Saferoom by using only a few snippets from saferoom rather than adding the whole dependency so this PR is redundant as I will have to start fresh... I will be closing this one and work on a new one...

**Pull request closed without merging**
