### PR TITLE
improve dashboard UI

### PR DESCRIPTION
**Pull request by CodeWithSouma**
## Improve dashboard UI
* remove constraint layout and add relative layout 
* add corner radius

### CODE REVIEW

**Comment by HerbertYiga** [comment]
Do we have a ticket Id for this so that you can add it here

**Comment by HerbertYiga** [comment]
You can have a look at this https://wiki.openmrs.org/display/docs/Pull+Request+Tips

**Comment by CodeWithSouma** [comment]
> Do we have a ticket Id for this so that you can add it here
My account has no permission to create a new issue, please help me.

**Comment by LuGO0** [comment]
> ## Improve dashboard UI
> * remove constraint layout and add relative layout
> * add corner radius

I dont think we are moving from constraint layout to relative layout @CodeWithSouma

**Comment by CodeWithSouma** [comment]
<pre>
 
</pre>

@LuGO0  sir please compare side by side if you don't like the work I can close the pull request. I sir don't think it is necessary to use constraint layout to create this type of simple layout.

**Comment by LuGO0** [comment]
@CodeWithSouma please create a Issue first get it approved by the maintainer (cc @rishabh-997 ) otherwise you might waste your efforts.
for creating an Issue first create a request to the helpdesk and then get the rights of JIRA to create and view Issues. I hope it helps

**Comment by CodeWithSouma** [comment]
@rishabh-997 sir I can't able to log in the @OpenMRS issue page it  Sorry, your userid is required to answer a CAPTCHA question correctly. but I entered the correct CAPTCHA why it does not permit me to login ???

**Comment by LuGO0** [comment]
@rishabh-997 I think we should close this now 👍

**Comment by LuGO0** [comment]
> @rishabh-997 sir I can't able to log in the @openmrs issue page it Sorry, your userid is required to answer a CAPTCHA question correctly. but I entered the correct CAPTCHA why it does not permit me to login ???

@CodeWithSouma you should raise a ticket with the OpenMRS helpdesk to gain access to the openMRS Issues JIRA page.

**Comment by rishabh-997** [comment]
Unnecessary and Abandoned!!! Create an issue if you need to work on it.

**Pull request closed without merging**
