### PR TITLE
Fixed AC-164

### PR DESCRIPTION
**Pull request by brainbreaker**
Corrected the argument being passed to the function `showStartVisitImpossibleDialog()`. This function should have patient name as argument.

### CODE REVIEW

**Comment by AvijitGhosh82** [comment]
Please remove additional commits.

**Comment by bholagabbar** [comment]
@AvijitGhosh82 The correct term would be 'Squashing additional commits' :)

**Comment by AvijitGhosh82** [comment]
@bholagabbar Haha..although the previous commits were actually pull requests from the master. @brainbreaker I would recommend you to do a `pull --rebase` from master before adding changes, it will remove the extra commit messages in the future.

**Comment by brainbreaker** [comment]
@AvijitGhosh82 I am closing this PR and creating a new one

**Comment by brainbreaker** [comment]
You can delete it

**Comment by downeym** [comment]
@brainbreaker 👍

**Comment by brainbreaker** [comment]
@AvijitGhosh82 My bad, didn't checked that PR has been updated, reopening it. Ignore the previous comments.

**Comment by bholagabbar** [comment]
@AvijitGhosh82 we resolved this issue over IRC. I think the PR is good to go assuming it's fixing the issue

**Comment by AvijitGhosh82** [comment]
Merged. Thanks!

**Comment by AvijitGhosh82** [comment]
@bholagabbar he closed and updated the issue while both of us were commenting so there might have been some misunderstanding due to the time lag :) It is indeed fixed and good to go now, so I merged it.

**Pull request merged**
