### PR TITLE
AC-919 : Using View Binding in PatientVisitsFragment

### PR DESCRIPTION
**Pull request by LuGO0**
## Description of what I changed

1. Using View binding for PatientVisits Fragment.
2. taking care of leaks.

## Issue I worked on

JIRA Issue: https://issues.openmrs.org/browse/AC-919

## Checklist: I completed these to help reviewers :)

- [x] My pull request only contains **ONE single commit**
(the number above, next to the 'Commits' tab is 1).

- [ ] I have **added tests** to cover my changes. (If you refactored
existing code that was well tested you do not have to add tests)

- [x] All new and existing **tests passed**.

- [x] My pull request is **based on the latest changes** of the master branch.

### CODE REVIEW

**Comment by HerbertYiga** [comment]
thanks @LuGO0  you can also add a ticket id to your commit message

**Comment by LuGO0** [comment]
Sure @HerbertYiga I will do if it gets approved. Thanks !!

**Review by rishabh-997 — APPROVED** [review]
just take care of herberts comments, rest LGTM

**Comment by LuGO0** [comment]
sure @rishabh-997 I will update and then merge this commit.

**Pull request merged**
