### PR TITLE
AC-845 bumped up versions and fixed deprecation Issues 

### PR DESCRIPTION
**Pull request by LuGO0**
## Description of what I changed
Bumped up dependency and Added //TODO comments for AC-861 a new Sub-Task to remove this customized dependency once the official version is released untill then we will use this patch.

## Issue I worked on

JIRA Issue: https://issues.openmrs.org/browse/AC-845

## Checklist: I completed these to help reviewers :)

- [x] My pull request only contains **ONE single commit**
(the number above, next to the 'Commits' tab is 1).

- [ ] I have **added tests** to cover my changes. (If you refactored
existing code that was well tested you do not have to add tests)

- [x] All new and existing **tests passed**.

- [x] My pull request is **based on the latest changes** of the master branch.

### CODE REVIEW

**Comment by LuGO0** [comment]
@rishabh-997 please review !!

**Comment by LuGO0** [comment]
@rishabh-997 please review !!

**Comment by rishabh-997** [comment]
> @rishabh-997 please review !!

I still haven't downloaded Android Studio :laughing: :rofl:

**Comment by LuGO0** [comment]
@rishabh-997 can we merge this PR, some new PRs might create warings with this PR.

**Review by rishabh-997 — APPROVED** [review]
LGTM... :fire:

**Pull request merged**
