### PR TITLE
AC-721 Remove unused imports

### PR DESCRIPTION
**Pull request by Abdelaty**
## Issue I worked on

JIRA Issue: https://issues.openmrs.org/browse/AC-721

## Checklist: I completed these to help reviewers :)

- [x] My pull request only contains **ONE single commit**
(the number above, next to the 'Commits' tab is 1).

- [ ] I have **added tests** to cover my changes. (If you refactored
existing code that was well tested you do not have to add tests)

- [x] All new and existing **tests passed**.

- [x] My pull request is **based on the latest changes** of the master branch.

### CODE REVIEW

**Comment by AryanGanotra07** [comment]
Hi @Abdelaty , please don't make pull requests unless your issue is ready for work. The pull requests will be merged only when mentor makes it ready for work.

**Comment by Abdelaty** [comment]
@AryanGanotra07  Thank you Aryan, Will take care next time.

**Comment by Abdelaty** [comment]
@f4ww4z Ok, I will add it. Thanks

**Comment by AryanGanotra07** [comment]
> @AryanGanotra07 Thank you Aryan, Will take care next time.

No problem @Abdelaty :) .

**Comment by Abdelaty** [comment]
Thank you 

> LGTM @Abdelaty

**Pull request merged**
