### PR TITLE
AC-142 Migrate to gradle and build on Android Studio	

### PR DESCRIPTION
**Pull request by AvijitGhosh82**

### CODE REVIEW

**Comment by AvijitGhosh82** [comment]
@KamilKalfas @rkorytkowski Please see if this can be merged. I've made some changes from KK's branch so that it builds successfully on AStudio. Also note, the current build uses Apache HTTP, which is not recommended by Google since Api23, although I've added the legacy http support in gradle, my next target would be to migrate completely to Volley, for better speed and thread handling capabilities.

**Comment by rkorytkowski** [comment]
@AvijitGhosh82, that's a lot of changes... They can't be easily reviewed. Please rewrite the documentation for developers so that I can at least test if I can build and run the project after migrating to gradle and all works correctly.

**Comment by AvijitGhosh82** [comment]
@rkorytkowski Done. Please let me know if this works.

**Comment by AvijitGhosh82** [comment]
Done, did it compile successfully?

Also I have another slight problem, the issues posted are on JIRA. Could
you kindly point me to a way I can get familiarized with JIRA+GitHub? Or
maybe we could move to Github issues? I have solved some of the issues
here:
https://issues.openmrs.org/browse/AC-141?jql=project%20%3D%20AC%20and%20resolution%20is%20empty


But I don't know how to report under them, given that PRs are to be sent
over github.

Regards,





*Avijit Ghosh*
*Android Facilitator, Google Students Club,*





*Kharagpur Open Source SocietySecond Year Undergraduate Student Department
of Chemical Engineering / Financial EngineeringIIT Kharagpur**Facebook
<https://www.facebook.com/AvijitGhosh82> , **LinkedIn
<https://in.linkedin.com/pub/avijit-ghosh/8a/b04/656> *

*Contact: +91 8902551989*

**Comment by rkorytkowski** [comment]
It builds fine, but when I try to run it in an emulator the application stops working and the following exception is thrown: {code}02-08 16:07:14.344 3045-3045/org.openmrs.mobile E/AndroidRuntime: FATAL EXCEPTION: main
                                                                  Process: org.openmrs.mobile, PID: 3045
                                                                  java.lang.UnsatisfiedLinkError: dlopen failed: /data/app/org.openmrs.mobile-1/lib/x86/libsqlcipher_android.so: has text relocations
                                                                      at java.lang.Runtime.loadLibrary(Runtime.java:372)
                                                                      at java.lang.System.loadLibrary(System.java:1076)
                                                                      at net.sqlcipher.database.SQLiteDatabase.loadLibs(SQLiteDatabase.java:113)
                                                                      at net.sqlcipher.database.SQLiteDatabase.loadLibs(SQLiteDatabase.java:107)
                                                                      at org.openmrs.mobile.application.OpenMRS.initializeSQLCipher(OpenMRS.java:207)
                                                                      at org.openmrs.mobile.application.OpenMRS.onCreate(OpenMRS.java:38)
                                                                      at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1013)
                                                                      at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4707)
                                                                      at android.app.ActivityThread.-wrap1(ActivityThread.java)
                                                                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1405)
                                                                      at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                      at android.os.Looper.loop(Looper.java:148)
                                                                      at android.app.ActivityThread.main(ActivityThread.java:5417)
                                                                      at java.lang.reflect.Method.invoke(Native Method)
                                                                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
02-08 16:07:16.864 3045-3045/org.openmrs.mobile I/Process: Sending signal. PID: 3045 SIG: 9
{code}
Do you have any clues how to fix that? Also I recall there was an issue running tests when using Android Studio... Is there any way to run tests now?

**Comment by AvijitGhosh82** [comment]
@rkorytkowski I ran the tests on an actual android device. From the errors it looks like the sqlcipher library that OpenMRS has been using isn't updated. 
https://github.com/sqlcipher/android-database-sqlcipher/issues/190

Solution: To remove the old .so lib files and use the new .aar package. I shall do the same and report back.

**Comment by AvijitGhosh82** [comment]
@rkorytkowski  Please check if this is working. I could not test it extensively, but I think your error is fixed. Also, I've set the target SDK as 22 because 23 requires explicit permission handling, because of which the app was crashing. Until such permission errors are caught everywhere they occur, we should build against 22.

**Comment by AvijitGhosh82** [comment]
Merged commits from Pull request #104 and closed it.

**Comment by rkorytkowski** [comment]
All worked! I will merge in the changes.

**Pull request merged**
