### PR TITLE
AC-712 Fixed Text Alignment in ShowcaseView

### PR DESCRIPTION
**Pull request by NullByte08**
## Description of what I changed

I fixed the text alignment of the description of "Register Patient" and "Form Entry" in Showcase view.
Screenshot_2020-02-18-22-11-10-302_org openmrs mobile
Screenshot_2020-02-18-22-11-13-448_org openmrs mobile

## Issue I worked on

JIRA Issue: https://issues.openmrs.org/browse/AC-712

## Checklist: I completed these to help reviewers :)

- [x] My pull request only contains **ONE single commit**
(the number above, next to the 'Commits' tab is 1).

- [ ] I have **added tests** to cover my changes. (If you refactored
existing code that was well tested you do not have to add tests)

- [x] All new and existing **tests passed**.

- [x] My pull request is **based on the latest changes** of the master branch.

### CODE REVIEW

**Comment by rishabh-997** [comment]
Is the layout working fine in case of `Find Patients` and `Active Visits` showcase ??? share the screenshot as well if working fine...

**Comment by f4ww4z** [comment]
@NullByte08 Did you request a code review in the JIRA page?

**Comment by f4ww4z** [comment]
> Is the layout working fine in case of `Find Patients` and `Active Visits` showcase ??? share the screenshot as well if working fine...

Also reply to this comment. @NullByte08

**Comment by NullByte08** [comment]
> Is the layout working fine in case of `Find Patients` and `Active Visits` showcase ??? share the screenshot as well if working fine...

Yes, All the layouts are working fine. I have checked them. Only these two were not working so I corrected them.

**Comment by NullByte08** [comment]
> @NullByte08 Did you request a code review in the JIRA page?

I have requested it now. Sorry, I am new to JIRA.

**Comment by rishabh-997** [comment]
> > @NullByte08 Did you request a code review in the JIRA page?
> 
> I have requested it now. Sorry, I am new to JIRA.

can you post a gif of the same.

**Comment by Abdelaty** [comment]
@NullByte08 Please Make sure that your PR based on the latest changes of the master branch. And you can have a look [here ](https://wiki.openmrs.org/display/docs/Pull+Request+Tips)and follow this tips before make a PR.

**Comment by NullByte08** [comment]
> @NullByte08 Please Make sure that your PR based on the latest changes of the master branch. And you can have a look [here ](https://wiki.openmrs.org/display/docs/Pull+Request+Tips)and follow this tips before make a PR.

I have checked it, and it is based on latest changes. I have edited my comment.

**Pull request merged**
