### PR TITLE
AC-682 fix Calender Icon in Register Patient Activity

### PR DESCRIPTION
**Pull request by 991rajat**
## Description of what I changed

Fix Calender Icon in Register Patient Activity

## Issue I worked on

JIRA Issue: https://issues.openmrs.org/browse/AC-682

## Checklist: I completed these to help reviewers :)

- [x] My pull request only contains **ONE single commit**
(the number above, next to the 'Commits' tab is 1).

- [ ] I have **added tests** to cover my changes. (If you refactored
existing code that was well tested you do not have to add tests)

- [x] All new and existing **tests passed**.

- [x] My pull request is **based on the latest changes** of the master branch.

### ScreenShot
Screenshot_20200207-225329

### CODE REVIEW

**Comment by ribhavsharma** [comment]
Hey, Looks Good! I'd suggest that you wait for the issue to be tagged "Ready for work" before making a PR in the future :)

**Comment by 991rajat** [comment]
ok, @ribhavsharma I'm new to this kind of system(JIRA).

**Comment by f4ww4z** [comment]
This looks good @991rajat , but you need to assign yourself [here](https://issues.openmrs.org/browse/AC-682) first.

**Comment by f4ww4z** [comment]
Closing this since @LuGO0 claimed this issue in JIRA.

**Pull request closed without merging**
