### PR TITLE
AC-130

### PR DESCRIPTION
**Pull request by pulkit4tech**
This implementation of issue mentioned at https://issues.openmrs.org/browse/AC-130

### CODE REVIEW

**Comment by robbyoconnor** [comment]
Squash the commits ;)

**Comment by pulkit4tech** [comment]
Thanks @robbyoconnor 
Closing this request and will be requesting new pull request. :)

**Comment by robbyoconnor** [comment]
No need to close this -- you can rebase and repush -- so open it and undelete your branch ;)

**Comment by robbyoconnor** [comment]
Always try to keep your pull requests to one commit. Google how to do interactive rebases if you do not know how :)

**Comment by AvijitGhosh82** [comment]
Looks good now. Merged.

**Comment by pulkit4tech** [comment]
Thanks @robbyoconnor and @AvijitGhosh82 :)

**Pull request merged**
