### PR TITLE
WebRTC APP FOR COMMUNICATING GCI-2015

### PR DESCRIPTION
**Pull request by Basarqari**

### CODE REVIEW

**Comment by Basarqari** [comment]
Please accept

**Comment by robbyoconnor** [comment]
I'm going to make this public record: did you write all of this? Is this WHOLLY your work. Because what you did (and deleting your branch won't help you, I have it on my laptop) is enough get disqualified from the competition. You cannot remove attribution from code you do not own.

**Comment by robbyoconnor** [comment]
You literally copied a travis configuration file...you clearly didn't write this.

**Comment by downeym** [comment]
Substantial portions of this pull request have been copied from the All Rights Reserved / copyrighted code repository at https://github.com/opentok/OpenTokRTC. I am closing this pull request due to this copyright violation. If further licensing is made available from the owner of OpenTokRTC project, please update your repository and create a new pull request.

**Pull request closed without merging**
