### PR TITLE
AC-193 - Find Patients storyboard refactoring - WIP

### PR DESCRIPTION
**Pull request by tmarzeion**
Features:
- Removed Find Patients tabbed view, now its divided into to separated activities. When clicking Find Patients there is now "Synced Patients" displayed, with "Add Patient" button, which triggers "Download Patients" activity, and "Search", which enables user to filter local data by query.
- Add Patient View is displaying Last Viewed patients (by REST `ws/rest/v1/patient?lastviewed=&v=full` request), and it also got search feature which is looking for patients in remote database by RESTWS.
- Add Patient button is disabled when there is no Internet connection.
- There is progress bar that indices if REST process is in progress.

Refactoring notes:
I've did general refactoring, because separating fragments to activities affected bunch of code:
- Removed activity that were specialized in searching for remote patients, this function is now working in same activity that displays last viewed patients
- Separated patient RecyclerView adapters into two adapters (LastVieved and Synced) to make refactoring easier, I can merge those adapters again later.
- Merged LastViewedPatientListener and FindPatientListener
- Removed SwipeRefreshLayout, because it wasn't working and I think that It would be easier to implement this one from scratch instead of repairing it.
- Massive code logic cleanup

TODO:
- Add SwipeRefresh to LastViewed Activity - DONE
- Merge separated RecyclerView adapters - DONE (I will create ticket for that since it will be possible to merge 3 or even 4 adapters into one via builder or something like that)
- Some manual testing to catch possible bugs - DONE

PS. I suggest to test it on demo.openmrs.org, since devtest04.openmrs.org doesn't work and int02.openmrs.org doesn't show last viewed patients (I think we need ticket for that, because it isn't broken by my changes)

### CODE REVIEW

**Comment by tmarzeion** [comment]
@rkorytkowski @AvijitGhosh82 Check out changes I've made :)

**Comment by AvijitGhosh82** [comment]
One small thing, why did you add the + button in active visits activity? If at all there is a new button it should add a new visit, and not download new patients, what do you think? @tmarzeion

**Comment by tmarzeion** [comment]
@AvijitGhosh82 
I'll remove that `+` button.
It seems that Active visits view is using same menu bar layout :spaghetti: :smile:

**Comment by tmarzeion** [comment]
@AvijitGhosh82 
Fixed by hiding `+` button on `FindActiveVisitsActivity`'s `onCreateOptionsMenu`

**Comment by AvijitGhosh82** [comment]
Cool! I'll check it when you've committed the rest of your WIP :)

**Comment by tmarzeion** [comment]
@AvijitGhosh82 
I've done some manual testing of Active Visits feature:
- List animations looks bad because single containers are static and only text is animated.
- List holders would look better if they are sane as in Find Patient / Form Entry views.
- Searching function shouldn't trigger new activity, I think it should work exactly like search function in Find Patients - > Add patients
- Frequent ANR's, I will create some tickets for that if I'll find out how to reproduce them

I can take care of that after this pull :smiley:

**Comment by AvijitGhosh82** [comment]
Very well. Do you want this pull to get merged and work further in a new pull?

**Comment by tmarzeion** [comment]
@AvijitGhosh82 I think this can be merged if You think this code is OK :)

**Comment by AvijitGhosh82** [comment]
Merged. Thanks!

**Pull request merged**
