### PR TITLE
AC-992 : Improve dark mode 

### PR DESCRIPTION
**Pull request by prateek27das**
AC-992 Improve dark mode

## Description of what I changed
In Dark mode, theme of custom dialog is light which is straining to eyes in dark. I have
Changed it to dark theme.

### Before : 
LogOut                Select Location

## Here is a Short Video Demonstrating my work:
https://drive.google.com/file/d/183Wy5PNdKAqUI5Titx3w2LAtunwWMfNf/view?usp=sharing

## Issue I worked on

JIRA Issue: https://issues.openmrs.org/browse/AC-992

## Checklist: I completed these to help reviewers :)

- [ ] My pull request only contains **ONE single commit**
(the number above, next to the 'Commits' tab is 1).

- [ ] I have **added tests** to cover my changes. (If you refactored
existing code that was well tested you do not have to add tests)

- [x] All new and existing **tests passed**.

- [x] My pull request is **based on the latest changes** of the master branch.

### CODE REVIEW

**Comment by prateek27das** [comment]
@LuGO0 it will be a great act of kindness if you review the code and merge it and any assistance you might be able to render will be greatly appreciated.

**Comment by LuGO0** [comment]
Wont be a great act of kindness 😅, will surely review need some time.

**Comment by LuGO0** [comment]
just a quick review the ticket id is missing from PR title as well as the commit message!

**Comment by LuGO0** [comment]
Please remove files not relevant with the PR and attach a screenshot for the visual change.

**Comment by LuGO0** [comment]
Always add a screenshot or short video for any visual change you do. helps speed up the review !

**Review by LuGO0 — COMMENTED** [review]
Always add a screenshot or short video for any visual change you do. helps speed up the review !

**Comment by prateek27das** [comment]
@LuGO0 , I have removed the unnecessary files and attached the screenshot of previous condition and attached a video of the work I have done. Can you please review again?

**Comment by LuGO0** [comment]
Will review 👍

**Comment by LuGO0** [comment]
configuration file is still edited? just exclued the files not needed.

**Comment by prateek27das** [comment]
Screenshot 2022-02-20 at 10 01 27 AM
At my end it's showing that This File is deleted.

**Comment by LuGO0** [comment]
There is difference between deleting a file and excluding it from PR. I need that file to be excluded.

**Pull request closed without merging**
