### PR TITLE
AC-519 : Kotlin version error, causing build to fail: Fixed

### PR DESCRIPTION
**Pull request by sudoplox**
https://issues.openmrs.org/browse/AC-519

## Description of what I changed
Fixed the latest version of kotlin which was causing the build to fail

## Issue I worked on

JIRA Issue: https://issues.openmrs.org/browse/AC-519

## Checklist: I completed these to help reviewers :)

- [ X] My pull request only contains **ONE single commit**
(the number above, next to the 'Commits' tab is 1).

- [ ] I have **added tests** to cover my changes. (If you refactored
existing code that was well tested you do not have to add tests)

- [ X] All new and existing **tests passed**.

- [ X] My pull request is **based on the latest changes** of the master branch.

### CODE REVIEW

**Comment by f4ww4z** [comment]
@sudoplox Did you take a look at the failed Travis build?

Also, please read our https://wiki.openmrs.org/display/docs/Pull+Request+Tips and follow it. Thanks.

**Comment by sudoplox** [comment]
@f4ww4z Hey, I looked up and tried to fix the error again, can you have a look?

**Comment by f4ww4z** [comment]
@sudoplox Did you take a look at the failed Travis build? The error is straight forward. https://travis-ci.org/openmrs/openmrs-contrib-android-client/builds/487533020#L954

**Comment by f4ww4z** [comment]
@sudoplox did you get time to fix the travis build error? https://travis-ci.org/openmrs/openmrs-contrib-android-client/builds/487533020#L954

**Comment by f4ww4z** [comment]
Closing this PR due to inactivity. @sudoplox ping me to reopen when you are ready to work on it.

**Comment by sudoplox** [comment]
Hey @f4ww4z I believe the bug is already fixed by just enabling Multidex as there is a limit on methods and classes on the DEX file, generated after the building process. It is safe to enable it too as it doesn't affect any other functionality

**Pull request closed without merging**
