### PR TITLE
AC-560 Wrap Parent layout to match text size in charts list

### PR DESCRIPTION
**Pull request by VibhorChinda**
## Description of what I changed
Wrap Parent layout to match text size in charts list and setting horizontal divider height to match parent.

## Issue I worked on
JIRA Issue: https://issues.openmrs.org/browse/AC-560

## Checklist: I completed these to help reviewers :)

- [x] My pull request only contains **ONE single commit**
(the number above, next to the 'Commits' tab is 1).

- [ ] I have **added tests** to cover my changes. (If you refactored
existing code that was well tested you do not have to add tests)

- [x] All new and existing **tests passed**.

- [x] My pull request is **based on the latest changes** of the master branch.

### CODE REVIEW

**Comment by VibhorChinda** [comment]
@f4ww4z  please have a look at the PR

**Comment by f4ww4z** [comment]
@VibhorChinda can you post a screenshot here?

**Comment by VibhorChinda** [comment]
Screenshot 2019-12-24 at 1 19 34 AM

**Comment by VibhorChinda** [comment]
@f4ww4z added the layout screenshot here please have a look. The vertical view now matches the height of its parent view

**Pull request merged**
