### PR TITLE
AC-342 :Implement RxJava in EncounterDAO

### PR DESCRIPTION
**Pull request by rhari991**

### CODE REVIEW

**Comment by AdamGrzybkowski** [comment]
@rhari991 Remember to change issue status on JIRA to Request code review

**Comment by rhari991** [comment]
My bad, forgot to do that.

**Comment by AdamGrzybkowski** [comment]
@rhari991 What about other methods form EncounterDAO ?

**Comment by rhari991** [comment]
@AdamGrzybkowski I wasn't sure if I should modify them or not, since they are not used in presenters and require immediate returns. Should I use toBlocking().first() for them ?

**Comment by AdamGrzybkowski** [comment]
That's a good question to be honest. If they are not blocking the main thread then we probably don't need that but on the other hand the Dao interface will be inconsistent which might be confusing... @rkorytkowski what do you think ?

**Comment by rkorytkowski** [comment]
I wouldn't push towards making interface methods consistently return Observable if there's no plan to make use of it and simply call toBlocking().first().

Moving forward let's switch to rxjava just in the places, which seem to be unresponsive for the user and make sense to be executed asynchronously.

**Comment by AdamGrzybkowski** [comment]
@rhari991 Can you change this to mach subscribe/unsubsribe pattern you introduced ?

**Comment by rhari991** [comment]
@AdamGrzybkowski done

**Pull request merged**
