### PR TITLE
AC-533 Adding IntroSlider for first time users

### PR DESCRIPTION
**Pull request by Asgardian8740**
AC-533 Adding IntroSlider for first time users

## Description of what I changed

I have added Intro Slider for the first time user.
Screenshot_20190321-153806
Screenshot_20190321-153810
Screenshot_20190321-153814
Screenshot_20190321-153918
Screenshot_20190321-153923
Screenshot_20190321-153934

I just messed up with my git by working on the same fork for AC-532.
Please review the commits done after ee0c978.

## Issue I worked on

JIRA Issue: https://issues.openmrs.org/browse/AC-533

## Checklist: I completed these to help reviewers :)

- [ ] My pull request only contains **ONE single commit**
(the number above, next to the 'Commits' tab is 1).

- [ ] I have **added tests** to cover my changes. (If you refactored
existing code that was well tested you do not have to add tests)

- [x] All new and existing **tests passed**.

- [x] My pull request is **based on the latest changes** of the master branch.

### CODE REVIEW

**Comment by Asgardian8740** [comment]
> @Asgardian8740 could you please squash all Commits to one. Please take a look at community contribution guidelines.Link:https://wiki.openmrs.org/display/docs/Pull+Request+Tips

Please read the description given with this PR.

**Comment by f4ww4z** [comment]
@Asgardian8740 You should close this PR as it has unrelated changes, like solving AC-532 in the same branch. This is a very bad practice. It's better to just focus on 1 PR first, especially when it's one of your first PRs for this project.

**Comment by f4ww4z** [comment]
@Asgardian8740 Then make a new PR that contains AC-533 solution only.

**Comment by Asgardian8740** [comment]
> @Asgardian8740 You should close this PR as it has unrelated changes, like solving AC-532 in the same branch. This is a very bad practice. It's better to just focus on 1 PR first, especially when it's one of your first PRs for this project.

Ok sir,
I am new to github and didnt knew much about issues that can be faced from such practice.
I apologise it.

**Comment by Asgardian8740** [comment]
> @Asgardian8740 Then make a new PR that contains AC-533 solution only.

Ok sir,will do this ASAP.

**Comment by f4ww4z** [comment]
@Asgardian8740 Are you still working on this?

**Comment by f4ww4z** [comment]
Closing due to inactivity.

**Pull request closed without merging**
