### PR TITLE
AC - 898 Migrated java classes to kotlin classes in model package

### PR DESCRIPTION
**Pull request by ShivanshGoel221B**
## Description of what I changed

I migrated the following 3 java classes to kotlin in the model package:
- Person.java
- PersonUpdate.java
- Patient.java

## Issue I worked on

JIRA Issue: https://issues.openmrs.org/browse/AC-898

## Checklist: I completed these to help reviewers :)

- [x] My pull request only contains **ONE single commit**
(the number above, next to the 'Commits' tab is 1).

- [ ] I have **added tests** to cover my changes. (If you refactored
existing code that was well tested you do not have to add tests)

- [x] All new and existing **tests passed**.

- [x] My pull request is **based on the latest changes** of the master branch.

### CODE REVIEW

**Comment by shivamsawlani02** [comment]
@ShivanshGoel221B why did you change so many files? Please edit only those files which are relevant to the issue.
Also first take the reporter's consent before working on an issue. If the reporter allows only then you can work on the issue.

**Review by sahuadarsh0 — COMMENTED** [review]
Only change files related to your JIRA Issue. Don't change other files which are not relevant to your issue. Create separate issues for that.

**Comment by ShivanshGoel221B** [comment]
> @ShivanshGoel221B why did you change so many files? Please edit only those files which are relevant to the issue.
> Also first take the reporter's consent before working on an issue. If the reporter allows only then you can work on the issue.

All right I will, but after changing these files, the rest of the files were showing errors, that is why I had to change them

**Comment by SalahoAmro** [comment]
Please fix the test that failed in Travis.

**Comment by ShivanshGoel221B** [comment]
> Please fix the test that failed in Travis.

@SalahoAmro Done that, thank you for the review.

**Review by Akshatji800 — COMMENTED** [review]
@ShivanshGoel221B just a suggestion according to the contribution guidelines one needs to squash the commits into a single commit if possible as I see 4 commits here. You can have a look through the "Squashing your commits" section in [this guide](https://github.com/openmrs/openmrs-contrib-android-client/blob/master/CONTRIBUTING.md) to get an idea about how to squash commits if u don't have the idea. If you have not squashed the commits purposely due to some reason then I apologize for giving a useless suggestion.

**Comment by ShivanshGoel221B** [comment]
> @ShivanshGoel221B just a suggestion according to the contribution guidelines one needs to squash the commits into a single commit if possible as I see 4 commits here. You can have a look through the "Squashing your commits" section in [this guide](https://github.com/openmrs/openmrs-contrib-android-client/blob/master/CONTRIBUTING.md) to get an idea about how to squash commits if u don't have the idea. If you have not squashed the commits purposely due to some reason then I apologize for giving a useless suggestion.

Done that.

**Comment by LuGO0** [comment]
Closing this for now. please open the PR again after fixing the merge conflicts. thanks

**Pull request closed without merging**
