### PR TITLE
[AC-946] Bug in the language switching feature

### PR DESCRIPTION
**Pull request by K1RA-16**
##Bug in the language switching feature.

## Description of what I changed

fixed the language error mentioned in JIRA AC-946

## Issue I worked on

https://issues.openmrs.org/projects/AC/issues/AC-946?filter=allopenissues

## Checklist: I completed these to help reviewers :)

- [x] My pull request only contains **ONE single commit**
(the number above, next to the 'Commits' tab is 1).

- [ ] I have **added tests** to cover my changes. (If you refactored
existing code that was well tested you do not have to add tests)

- [ ] All new and existing **tests passed**.

- [x] My pull request is **based on the latest changes** of the master branch.

### CODE REVIEW

**Comment by K1RA-16** [comment]
hi @LuGO0 im new to all this and i don't know much can you please guide me through this 
i just found out this issue to be reproduced again and also i found this on jira and it was unassigned and unresolved 
i changed the while to for loop in this commit and reduced the use of local variables.
i also fixed some layout xml bugs to make them work alright.
PS: can you please tell me how to comment on jira 
i can;t login to https://issues.openmrs.org/login.jsp
though i made a wiki and issue tracker request

**Comment by K1RA-16** [comment]
Found a pending issue on JIRA mentioned AC-690
rectified it by creating a png of the JIRA logo used in the animation of the splash screen.

**Comment by jwnasambu** [comment]
@K1RA-16 this sounds good and I really like your speed. I would like to recommend the following to make this work much better:

1. Before working on the issue ensure it's in the `ready for work state` then claim it. If it's not and you feel you can handle it, ask a senior dev to change the status. You can ping the following to help you on this @rishabh-997, @dkayiwa  or @ibacher. You can follow this link for more information https://wiki.openmrs.org/display/docs/Tickets

2. You can't have one PR for more thank 1 ticket. Each ticket requires its own PR.
3. Once you have fixed the issue, paste the PR link to the ticket and request for a review by changing the ticket status.

**Comment by K1RA-16** [comment]
@jwnasambu noted ma'am
actually the issue tracking service is not working right now i think.

**Comment by LuGO0** [comment]
Thank you @jwnasambu for the input, @K1RA-16  sorry for the late response please follow the steps and get the Issue ready before submitting a PR.

**Pull request closed without merging**
