### PR TITLE
feature: added Hindi translations for the app

### PR DESCRIPTION
**Pull request by athiranair2000**
##'AC-515-Language Translation'

## Issue I worked on

JIRA Issue: https://issues.openmrs.org/browse/AC-515

## Checklist: I completed these to help reviewers :)

- [x] My pull request only contains **ONE single commit**
(the number above, next to the 'Commits' tab is 1).

- [] I have **added tests** to cover my changes. (If you refactored
existing code that was well tested you do not have to add tests)

- [x] All new and existing **tests passed**.

- [x] My pull request is **based on the latest changes** of the master branch.

### CODE REVIEW

**Comment by f4ww4z** [comment]
Did you take a look at the OpenMRS PR tips? Please squash to 1 commit only.
Also, fix those codacy issues please. Thanks.

**Comment by f4ww4z** [comment]
@athiranair2000 Please refer to https://wiki.openmrs.org/display/docs/Pull+Request+Tips

**Comment by f4ww4z** [comment]
@athiranair2000 Have you seen the failing CI build?

**Comment by f4ww4z** [comment]
Closing this PR due to inactivity, failing build and the author of this PR is actively working on another one.

**Comment by athiranair2000** [comment]
I would like to work on malayalam and Hindi translations. I will try to fix
these as well.

**Comment by f4ww4z** [comment]
@athiranair2000 Fix your **open PRs** first before this one. Thanks.

**Comment by athiranair2000** [comment]
Okay @maharaja fawwaz

**Comment by athiranair2000** [comment]
Okay @maharaj fawwaz

**Pull request closed without merging**
