### PR TITLE
AC-851: Fix errors in inflating attr when using on View's background.

### PR DESCRIPTION
**Pull request by manjotsidhu**
## Description of what I changed

When using attribute as a View's background, the app crashes failing to inflate the View

## Issue I worked on

JIRA Issue: https://issues.openmrs.org/browse/AC-851

## Checklist: I completed these to help reviewers :)

- [x] My pull request only contains **ONE single commit**
(the number above, next to the 'Commits' tab is 1).

- [ ] I have **added tests** to cover my changes. (If you refactored
existing code that was well tested you do not have to add tests)

- [x] All new and existing **tests passed**.

- [x] My pull request is **based on the latest changes** of the master branch.

### CODE REVIEW

**Comment by LuGO0** [comment]
@manjotsidhu while doing this fix what problem you came across, what was the Issue with the earlier attributes? please explain your change and link this PR to the JIRA issue.

**Comment by manjotsidhu** [comment]
> @manjotsidhu while doing this fix what problem you came across, what was the Issue with the earlier attributes? please explain your change and link this PR to the JIRA issue.

App was getting crashed when loading Patients Dashboard activity faced by me and @LuGO0 . The logs are available at JIRA issue. This issue was due to the color attribute being applied to View's background. 

This thread also explains the same issue : https://stackoverflow.com/questions/17843635/how-to-use-textcolorprimary-as-background-color-in-a-style

**Comment by LuGO0** [comment]
@rishabh-997 The fix works for me but I dont know if there is some more elegant way of doing this rather than creating a whole new xml file ?

**Comment by manjotsidhu** [comment]
> @rishabh-997 The fix works for me but I dont know if there is some more elegant way of doing this rather than creating a whole new xml file ?

The recommended background to any View should be a drawable and the only way to define a drawable is to create a drawable with that color. 

I would give more information on this, API <= 21 doesn't allows referencing a platform attribute in style. Therefore, for backward compatibility we have to explicitly define a reference to that variable in `attrs.xml`.

**Comment by LuGO0** [comment]
@manjotsidhu @rishabh-997 is [this](https://github.com/LuGO0/openmrs-contrib-android-client/commit/bee0f9468e25b58da606357f9b3f0fb4da212e2a) a good way to fix this bug ??
I really feel the current fix is an overkill, @manjotsidhu  if the fix looks good and is approved by @rishabh-997 you can cherry pick the commits.

**Comment by manjotsidhu** [comment]
> @manjotsidhu @rishabh-997 is [this](https://github.com/LuGO0/openmrs-contrib-android-client/commit/bee0f9468e25b58da606357f9b3f0fb4da212e2a) a good way to fix this bug ??
> I really feel the current fix is an overkill, @manjotsidhu  if the fix looks good and is approved by @rishabh-997 you can cherry pick the commits. 

Not sure, the attribute which was created I guess is for dynamic theme changes that's why I think we can't use a static color instead of the attribute.

**Comment by LuGO0** [comment]
> Not sure, the attribute which was created I guess is for dynamic theme changes that's why I think we can't use a static color instead of the attribute.

I looked up the styles theme and I found 2 commented lines which contain these attributes, I dont know why are they commented maybe they would be satisfy the need.
here https://github.com/openmrs/openmrs-contrib-android-client/blob/master/openmrs-client/src/main/res/values/styles.xml#L31

**Review by lovingroshni15 — APPROVED** [review]
LGTM !!! Was quite busy with university exams so this review got a bit late :sweat_smile:

**Review by rishabh-997 — APPROVED** [review]
LGTM !!! Was quite busy with university exams so this review got a bit late :sweat_smile: 
I guess I was logged in with the wrong ID previously.

**Pull request merged**
