### PR TITLE
AC-219 merging patients when syncing

### PR DESCRIPTION
**Pull request by AdamGrzybkowski**
This PR adds merging feature. When you turn on syncing and there are unsynced patients that will match with with already existing patients new Activity will be shown. You can then register patient as new or merge with the existing one by selecting them and clicking merge button. If there are more patients you will see the same activity with new data. 

Screen: 
screenshot_1476698423

### CODE REVIEW

**Comment by AdamGrzybkowski** [comment]
@rkorytkowski @tmarzeion @AvijitGhosh82  I've updated the code.

**Comment by tmarzeion** [comment]
@AdamGrzybkowski 
Code looks good and it works fine.
Adam, please take a look on [THIS](https://www.youtube.com/watch?v=dQw4w9WgXcQ) before merging

**Comment by AdamGrzybkowski** [comment]
@tmarzeion Conflicts resolved

**Comment by dkayiwa** [comment]
@AdamGrzybkowski did you see the conflicts on this?

**Comment by AdamGrzybkowski** [comment]
Thanks @dkayiwa 
@tmarzeion conflicts resolved, do you think we can merge this ?

**Pull request merged**
