### PR TITLE
AC-195 show dialog with similar patients when registering new one

### PR DESCRIPTION
**Pull request by AdamGrzybkowski**
This PR contains commit from AC-196 PR because it requires those changes.  
I've some questions about the workflow:

1.In the current release when you register new user, you are redirect to the dashbord activity. Why not to the PatientDashbordActivity ? 
2. Why do we fetch patient in PatientDashbordActivity by uuid if we want to support offline mode? If we have more then one not synced patients we will always open the oldest one not synced. I quess this is a bug.

### CODE REVIEW

**Comment by AvijitGhosh82** [comment]
@AdamGrzybkowski , the workflow you are mentioning does sound like a better idea! While creating the new patient registration page this slipped my mind. Could you add a commit to fetch patient by ID (and not uuid) and open patientdashboardactivity just after a user is registered? 

Thanks!

**Comment by AdamGrzybkowski** [comment]
Sure ! :)

**Comment by AdamGrzybkowski** [comment]
@AvijitGhosh82 I have updated PR, this is almost ready. There 2 things left:
1. First we need to merge AC-203.
2. Could you help me with the similar_patient_row layout? I had to set background of each element to white to look it ok. But this is kind of a hack. Also what do you think about this layout? The strings with bold style means that those values are matching new patient that user tries to register. 

screenshot_1474641332

**Comment by AvijitGhosh82** [comment]
@AdamGrzybkowski , you might need to do a pull before the next commit, there's a merge conflict :)

**Comment by AdamGrzybkowski** [comment]
@AvijitGhosh82 done :)

**Comment by AvijitGhosh82** [comment]
@AdamGrzybkowski is this pull request ready for testing or you want to add anything else? :)

**Comment by AdamGrzybkowski** [comment]
Ready for testing :)

**Comment by AvijitGhosh82** [comment]
Adam, I was testing it locally using demo.openmrs.org server, and I get
"Unauthorized" as toast when I try to register a new patient.

**Comment by AdamGrzybkowski** [comment]
@AvijitGhosh82  I am able to successfully register new patient on demo.openmrs.org

**Comment by AvijitGhosh82** [comment]
Great, it worked for me just now as well. Extra brownie points for making the similar patient view clickable. Good job! Merging :)

**Pull request merged**
