### PR TITLE
AC 517: Added Malayalam translations

### PR DESCRIPTION
**Pull request by athiranair2000**
## Description of what I changed
Provided Malayalam translation to the app.

## Issue I worked on

JIRA Issue: https://issues.openmrs.org/browse/AC-517

## Checklist: I completed these to help reviewers :)

- [x] My pull request only contains **ONE single commit**
(the number above, next to the 'Commits' tab is 1).

- [ ] I have **added tests** to cover my changes. (If you refactored
existing code that was well tested you do not have to add tests)

- [x] All new and existing **tests passed**.

- [x] My pull request is **based on the latest changes** of the master branch.

### CODE REVIEW

**Comment by dkayiwa** [comment]
Did you see the travis build failure?

**Comment by f4ww4z** [comment]
@athiranair2000 did you see @dkayiwa 's comment?

**Comment by f4ww4z** [comment]
Closing due to inactivity. @athiranair2000 Ping me to reopen this when you want to resume.

**Comment by athiranair2000** [comment]
Thanks:) @Maharaj Fawwaz I will let you know whenever I come with a
solution.

Regards,
Athira Nair K
AmritaUniversity <https://www.amrita.edu/>
GitHub <https://github.com/athiranair2000>

**Pull request closed without merging**
