### PR TITLE
[AC-677]Changing screenshots in README.md

### PR DESCRIPTION
**Pull request by Devanshk9**
## Description of what I changed
I changed the old screenshots with the new one.
open2
open3
open1

## Issue I worked on

JIRA Issue: https://issues.openmrs.org/browse/AC-677

## Checklist: I completed these to help reviewers :)

- [x] My pull request only contains **ONE single commit**
(the number above, next to the 'Commits' tab is 1).

- [x] I have **added tests** to cover my changes. (If you refactored
existing code that was well tested you do not have to add tests)

- [ ] All new and existing **tests passed**.

- [ ] My pull request is **based on the latest changes** of the master branch.

### CODE REVIEW

**Comment by Devanshk9** [comment]
Will add more once demo server is back.

**Comment by ribhavsharma** [comment]
@Devanshk9 Did you create an issue for this?

**Comment by Devanshk9** [comment]
> @Devanshk9 Did you create an issue for this?

Yes @ribhavsharma https://issues.openmrs.org/browse/AC-671

**Comment by Devanshk9** [comment]
@f4ww4z sir have a say on this PR.

**Comment by rishabh-997** [comment]
LGTM. Good work with your first issue @Devanshk9

**Pull request merged**
