### PR TITLE
AC-890 :Fixed language English option text is displayed correctly.

### PR DESCRIPTION
**Pull request by sahuadarsh0**
## Description of what I changed
I have added spinner style and applied it to the Language button English option to make it display correctly across all devices

## Issue I worked on
JIRA Issue: https://issues.openmrs.org/browse/AC-890

## Checklist: I completed these to help reviewers :)
- [x] My pull request only contains **ONE single commit**
(the number above, next to the 'Commits' tab is 1).

- [ ] I have **added tests** to cover my changes. (If you refactored
existing code that was well tested you do not have to add tests)

- [x] All new and existing **tests passed**.

- [x] My pull request is **based on the latest changes** of the master branch.

Image

### CODE REVIEW

**Review by amtheshubham — COMMENTED** [review]
As mentioned in the AC-890 issue, It is not displayed correctly in "some devices". Please test with different screen sizes (small sizes) in the emulator and post screenshots of each device. Also, please don't start working on an issue right after creating it. Wait for the collaborators to comment on it.

**Comment by rishabh-997** [comment]
Please wait for maintainers to make the issue ready for work, as sometimes it causes unnecessary efforts like in this one. Also, don't create PR's for issues without the reporter's consent.

**Comment by sahuadarsh0** [comment]
> Please wait for maintainers to make the issue ready for work, as sometimes it causes unnecessary efforts like in this one. Also, don't create PR's for issues without the reporter's consent.

This was my first PR and I was unaware of the whole process. Shall I close the PR?

**Comment by HerbertYiga** [comment]
> > Please wait for maintainers to make the issue ready for work, as sometimes it causes unnecessary efforts like in this one. Also, don't create PR's for issues without the reporter's consent.
> 
> This was my first PR and I was unaware of the whole process. Shall I close the PR?

@LuGO0 would you like to assess the ticket for this pr

**Comment by sahuadarsh0** [comment]
> > > Please wait for maintainers to make the issue ready for work, as sometimes it causes unnecessary efforts like in this one. Also, don't create PR's for issues without the reporter's consent.
> > 
> > 
> > This was my first PR and I was unaware of the whole process. Shall I close the PR?
> 
> @LuGO0 would you like to assess the ticket for this pr

Yeah But Someone is already working on it and this issue was not created by me

**Comment by rishabh-997** [comment]
@LuGO0 continuing the discussion on Jira, finalize the ticket status please

**Comment by LuGO0** [comment]
sorry @sahuadarsh0, the reporter has claimed the Issue you can close this now.

**Comment by sahuadarsh0** [comment]
No problem

**Pull request closed without merging**
