### PR TITLE
AC-331 Problem in editing patient's Vital Form

### PR DESCRIPTION
**Pull request by AdamGrzybkowski**
I have added TextView above each numeric field. See below
screenshot_1485433580

### CODE REVIEW

**Comment by AdamGrzybkowski** [comment]
@shivtej1505 I agree this looks strange to have it twice but this is rather how this form is created(other forms seems fine?) or bug in creating layout that is not part of this ticket. But I think it is the option nr 1

**Comment by AvijitGhosh82** [comment]
@shivtej1505 I was wondering the same thing when I was first designing this page, and it would appear that the form happens to have the form title and page title same. If the form had other pages this would not be an issue. 

@AdamGrzybkowski  I'd suggest to add a bit of padding to the left of the question texts so that it looks neater.

**Comment by AdamGrzybkowski** [comment]
@AvijitGhosh82 I've increased left margin and replaced screenshot above with the new one

**Comment by tmarzeion** [comment]
@AdamGrzybkowski Doubled `vitals` label is caused by form resource, not android app itself :hamburger:

**Pull request merged**
