### PR TITLE
AC-406 : Minor Visual Improvements

### PR DESCRIPTION
**Pull request by DefCon-007**
I have added the TextInputLayout for the EditTexts. 
screenshot_1497777936

I have also replaced the EditText fields in the form with a SeekBar.
screenshot_1497778570

### CODE REVIEW

**Comment by dkayiwa** [comment]
@AvijitGhosh82 do you think this is ready for merging? 😊

**Comment by AvijitGhosh82** [comment]
No, I actually asked him to fix something in the forms, and qa refapp has
no forms to work on. Could you please add forms in the server, I'm unable
to do it, it's holding us up...

**Comment by dkayiwa** [comment]
@AvijitGhosh82 i asked a follow up question on the talk thread.

**Comment by dkayiwa** [comment]
@DefCon-007 @AvijitGhosh82 are these merge conflicts caused by the fact that you already have these changes in?

**Comment by AvijitGhosh82** [comment]
Due to merging of another PR. The gradle file has been modified.




*Avijit Ghosh*
*Senior Advisor,*



*Kharagpur Open Source SocietyThird Year Undergraduate Student Department
of Chemical Engineering/ Financial EngineeringIIT Kharagpur*

*Facebook <https://www.facebook.com/AvijitGhosh82> , **LinkedIn
<https://in.linkedin.com/pub/avijit-ghosh/8a/b04/656> , GitHub
<http://github.com/AvijitGhosh82>*

*Contact: +91 8902551989*

**Comment by dkayiwa** [comment]
@DefCon-007 @AvijitGhosh82 should i just close this? 😊

**Comment by dkayiwa** [comment]
@DefCon-007 and @AvijitGhosh82 ping me to reopen if you feel otherwise.

**Comment by AvijitGhosh82** [comment]
Hey @dkayiwa I'm opening this. I sat with @DefCon-007 and we've split the code into the relevant issues.

**Pull request merged**
