### PR TITLE
AC-450 :  Added Addmisions Form

### PR DESCRIPTION
**Pull request by VANKINEENITAWRUN**
## Issue I worked on

JIRA Issue: https://issues.openmrs.org/browse/AC-450

## Checklist: I completed these to help reviewers :)

- [x] My pull request only contains **ONE single commit**
(the number above, next to the 'Commits' tab is 1).

- [ ] I have **added tests** to cover my changes. (If you refactored
existing code that was well tested you do not have to add tests)

- [x] All new and existing **tests passed**.

- [x] My pull request is **based on the latest changes** of the master branch.
Screenshot_2019-03-21-06-56-06-1866739274

### CODE REVIEW

**Comment by VANKINEENITAWRUN** [comment]
@Rimjhim28 The issue is not closed yet. Updated the description.

**Comment by Rimjhim28** [comment]
My bad @VANKINEENITAWRUN!
Still it's better to work on pull requests once the issues are ready for work! :)

**Comment by VANKINEENITAWRUN** [comment]
@Rimjhim28 before it was Ready for work then I claimed. Now I changed the status to codeReview.

**Comment by f4ww4z** [comment]
Thanks for the PR @VANKINEENITAWRUN, but this is not how an admission form looks like.

image

See the screenshot for the Web app version of the 'Admit to Inpatient' form.

**Comment by dkayiwa** [comment]
@VANKINEENITAWRUN are you still working on this?

**Comment by VANKINEENITAWRUN** [comment]
@f4ww4z  I have added a comment in Jira please check it, if it's not relevant then can close the issue.

**Comment by f4ww4z** [comment]
@VANKINEENITAWRUN answered.

**Comment by f4ww4z** [comment]
Closing this as requested.

**Pull request closed without merging**
