### PR TITLE
AC-500 Missing validation on patient's name during registration ​

### PR DESCRIPTION
**Pull request by Siddhant9868**
## Description of what I changed
Made numbers to be an invalid character in name fields in the registration form of a new patient.
Changed the error message to be more helpful.
Fixed the alignment of the error box changed due to the changed error message.

## Issue I worked on
JIRA Issue: https://issues.openmrs.org/browse/AC-500

## Checklist: I completed these to help reviewers :)

- [x] My pull request only contains **ONE single commit**
(the number above, next to the 'Commits' tab is 1).

- [ ] I have added tests to cover my changes. (If you refactored
existing code that was well tested you do not have to add tests)

- [x] All new and existing **tests passed**.

- [x] My pull request is **based on the latest changes** of the master branch.

### CODE REVIEW

**Comment by Siddhant9868** [comment]
The issue was unresolved because the test used the sample names as `given_name_1, middle_name_1` etc.
That caused the tests to fail.
After the debugging the tests I figured that out and replaced the sample names to be `given_name_a, middle_name_a`, etc.
I fixed that in the second commit.

**Comment by f4ww4z** [comment]
Thanks for the PR @Siddhant9868 . Can you attach the new UI as a recording / screenshot in the JIRA issue? Also, please squash the 2 commits.

**Comment by f4ww4z** [comment]
@Siddhant9868 The UI looks good!. Did you see the merge conflict? Please resolve it.

**Comment by Siddhant9868** [comment]
The merge conflict is resolved.

**Comment by f4ww4z** [comment]
@Siddhant9868 Squash?

**Comment by f4ww4z** [comment]
@Siddhant9868 Rename the commit to `AC-500: <description here>`

**Comment by Siddhant9868** [comment]
@f4ww4z There are merges after this PR. I am closing this PR and would create a new PR with the same changes.

**Pull request closed without merging**
