### PR TITLE
AC-575: Added password reset

### PR DESCRIPTION
**Pull request by deepak140596**
## Description of what I changed

Added Password Reset.

## Issue I worked on

JIRA Issue: https://issues.openmrs.org/browse/AC-575

## Checklist: I completed these to help reviewers :)

- [x] My pull request only contains **ONE single commit**
(the number above, next to the 'Commits' tab is 1).

- [ ] I have **added tests** to cover my changes. (If you refactored
existing code that was well tested you do not have to add tests)

- [x] All new and existing **tests passed**.

- [x] My pull request is **based on the latest changes** of the master branch.

### CODE REVIEW

**Comment by deepak140596** [comment]
@f4ww4z , Please check this.

**Comment by f4ww4z** [comment]
I'm currently trying to make a local openmrs server, but still failing with error
```
???Error executing sql: create database if not exists `?` default character set utf8 - Could not create connection to database server. Attempted reconnect 3 times. Giving up.???
```
When I resolve this, I'll test this PR thoroughly.

**Comment by deepak140596** [comment]
@f4ww4z , that error occurs because the MySQL is running on different PORT or isn't configured properly.
Also testing this will be quite a tiresome task as you would have to update the user's table and in my case while testing, Object not found error was occurring quite often.

I would suggest to wait until the WebApp is properly configured (which should be done by this week). Once it is done, we can thoroughly test it.

**Comment by f4ww4z** [comment]
> WebApp is properly configured

@deepak140596 Is there any status or link for us to check this?

**Comment by f4ww4z** [comment]
closing due to inactivity.

**Pull request closed without merging**
