### PR TITLE
AC-553 | AC-563 | AC-526 RESOLVED

### PR DESCRIPTION
**Pull request by nishchalraj**
## Issue I worked on

JIRA Issue: https://issues.openmrs.org/browse/AC-553
JIRA Issue: https://issues.openmrs.org/browse/AC-563
JIRA Issue: https://issues.openmrs.org/browse/AC-526

# Checklist: I completed these to help reviewers :)

- [ ] My pull request only contains **ONE single commit**
(the number above, next to the 'Commits' tab is 1).

- [ ] I have **added tests** to cover my changes. (If you refactored
existing code that was well tested you do not have to add tests)

- [x] All new and existing **tests passed**.

- [x] My pull request is **based on the latest changes** of the master branch.

### CODE REVIEW

**Comment by nishchalraj** [comment]
I am also seeing a lot of errors in the codebase and would like to change it if I get accepted. There are many redundant casts and overriding. Even the access assifiers need to be changed along with many other new issues I am seeing.

**Comment by nishchalraj** [comment]
Issues resolved: 
JIRA Issue: https://issues.openmrs.org/browse/AC-563

**Comment by nishchalraj** [comment]
AC-563 was done earlier but I saw it unresolved and hence added it too in my PR.

**Comment by f4ww4z** [comment]
Hi @nishchalraj , thanks for the PRs, but please follow our PR guidelines at https://wiki.openmrs.org/display/docs/Pull+Request+Tips . 1 PR should be for 1 JIRA issue only, and only work on it if you have claimed the issue on JIRA. See that all the JIRA issues that you fixed has already someone else assigned to it (working on it), so you can pick another issue to work on.

**Comment by nishchalraj** [comment]
There was no option to claim it, hence I went direct for the resolution.

**Comment by nishchalraj** [comment]
@f4ww4z i would also like to add that, i tried to resolve these issues as they were not completed, and i tried to do it quickly. There was no place i could have found to claim an assigned issue.

**Pull request closed without merging**
