### PR TITLE
AC-638 Adding inputType for capitalising the first letter

### PR DESCRIPTION
**Pull request by tbagz104**
## Description of what I changed

- As some of the important input fields were having just a text input in lowercase, such as '**City**','**First Name**' etc.,an input of capitalising the the first letter needs to be added as these fields are of high priority.

- Changed input type from `android:inputType="text"` to `android:inputType="textCapWords" ` which was missing for some important input fields.

## Issue I worked on

JIRA Issue: https://issues.openmrs.org/browse/AC-638

## Checklist: I completed these to help reviewers :)

- [x] My pull request only contains **ONE single commit**
(the number above, next to the 'Commits' tab is 1).

- [ ] I have **added tests** to cover my changes. (If you refactored
existing code that was well tested you do not have to add tests)

- [x] All new and existing **tests passed**.

- [x] My pull request is **based on the latest changes** of the master branch.

### CODE REVIEW

**Comment by tbagz104** [comment]
@f4ww4z could you please look into this ? :)

**Comment by rishabh-997** [comment]
> @f4ww4z could you please look into this ? :)

Go through the PR guidelines @tbagz104 , send the PR only when the issue is ready for work

**Comment by tbagz104** [comment]
> > @f4ww4z could you please look into this ? :)
> 
> Go through the PR guidelines @tbagz104 , send the PR only when the issue is ready for work

My bad,I didn't go through it. I've noted this. Thanks for pointing it out. I've pinged @f4ww4z on the issue page,hopefully he'll assess and make it ready for work. I hope that's okay for once.

**Comment by tbagz104** [comment]
> Looks good @tbagz104 . Please claim the task first on JIRA.

@f4ww4z Thanks :) It's done.

**Pull request merged**
