### PR TITLE
AC- 711 Update the GitHub version badge in readme.md 

### PR DESCRIPTION
**Pull request by AryanGanotra07**
## Description of what I changed
I have only updated the GitHub badge version from 2.6.1 to latest release v2.8.1 in readme.md
 
 ## Issue I worked on
 JIRA Issue: https://issues.openmrs.org/browse/AC-711
 
 ## Checklist: I completed these to help reviewers :)
 * [x]  My pull request only contains **ONE single commit**
   (the number above, next to the 'Commits' tab is 1).
 
 * [ ]  I have **added tests** to cover my changes. (If you refactored
   existing code that was well tested you do not have to add tests)
 
 * [x]  All new and existing **tests passed**.
 
 * [x]  My pull request is **based on the latest changes** of the master branch.

### CODE REVIEW

**Comment by AryanGanotra07** [comment]
> Did you created an issue first in openMRS jira ?

Yes I have created an issue in openMRS Jira portal.

**Comment by VibhorChinda** [comment]
> > Did you created an issue first in openMRS jira ?
> 
> Yes I have created an issue in openMRS Jira portal.

oh nice @AryanGanotra07 but please have a look at the PR tips (https://wiki.openmrs.org/display/docs/Pull+Request+Tips) these will help you for submitting the PR.

**Comment by f4ww4z** [comment]
> Yes I have created an issue in openMRS Jira portal.

@AryanGanotra07 Please use the PR template in your description and state the issue link.

**Comment by AryanGanotra07** [comment]
> > Yes I have created an issue in openMRS Jira portal.
> 
> @AryanGanotra07 Please use the PR template in your description and state the issue link.

I have edited the template as per the requirement. Please look into the pull request.

**Comment by AryanGanotra07** [comment]
@f4ww4z please review this?

**Pull request merged**
