### PR TITLE
AC 563: Show/Hide password brings cursor of EditText to beginning

### PR DESCRIPTION
**Pull request by vansha10**
## Description of what I changed

Fixes issue of cursor going to the beginning of EditText on toggling show/hide password.
Now, the cursor stays at the end of the EditText.

## Issue I worked on

JIRA Issue: https://issues.openmrs.org/browse/AC-563

## Checklist: I completed these to help reviewers :)

- [x] My pull request only contains **ONE single commit**
(the number above, next to the 'Commits' tab is 1).

- [ ] I have **added tests** to cover my changes. (If you refactored
existing code that was well tested you do not have to add tests)

- [x] All new and existing **tests passed**.

- [x] My pull request is **based on the latest changes** of the master branch.

## GIFs

**Before**
password_cursor_before

**After**
password_cursor_after

### CODE REVIEW

**Comment by vansha10** [comment]
> @vansha10 you should not be putting up pull requests unless mentotrs review your jira ticket and label it Ready For Work

I'm sorry. I'll keep that in mind next time.

**Comment by Abdelaty** [comment]
Good work @vansha10 
but As @VANKINEENITAWRUN  mentioned you should follow the PR Guidelines first.

**Comment by f4ww4z** [comment]
Thanks for the PR @vansha10 . But what happens if the cursor is in the middle of the text, and he/she hits the button?

**Comment by vansha10** [comment]
> Thanks for the PR @vansha10 . But what happens if the cursor is in the middle of the text, and he/she hits the button?

It goes to the end, but it should stay at the middle.
Thanks for pointing this out.
I'll fix this and make another pull request soon.

**Comment by vansha10** [comment]
@f4ww4z Link to [New Pull Request:](https://github.com/openmrs/openmrs-contrib-android-client/pull/523) 
Closing this one.

**Pull request closed without merging**
