### PR TITLE
AC-541: Handling multiple network calls

### PR DESCRIPTION
**Pull request by Rimjhim28**
## Description of what I changed

Added ```android:configChanges="orientation|screenSize|keyboardHidden"``` so that the activity is not destroyed and created by itself when the device is rotated, preventing the unnecessary network calls on device rotation.
Added ```viewPager.setOffscreenPageLimit(adapter.getCount()-1);``` so that all the fragments are loaded at once and to prevent the recreation of fragment each time when switched between tabs.

## Issue I worked on

JIRA Issue: https://issues.openmrs.org/browse/AC-541

## Checklist: I completed these to help reviewers :)

- [x] My pull request only contains **ONE single commit**
(the number above, next to the 'Commits' tab is 1).

- [ ] I have **added tests** to cover my changes. (If you refactored
existing code that was well tested you do not have to add tests)

- [x] All new and existing **tests passed**.

- [x] My pull request is **based on the latest changes** of the master branch.

### CODE REVIEW

**Comment by f4ww4z** [comment]
@Rimjhim28 I think there should be a **refresh** button in the app bar (or maybe an automatic Snackbar when there's new data available?) that updates the UI according to the data in the OpenMRS server. Please add that functionality in this PR.

**Comment by Rimjhim28** [comment]
@f4ww4z Isn't the sync button (rounded arrow) on the app bar doing the same thing?
I did the following:
1. Downloaded a patient from web server
2. Opened the patient on the patient dashboard
3. Changed the birth date on the web server
4. Clicked the sync button located on the app bar 
5. The changed birth date was reflected on the android screen

Isn't this what refresh button supposed to do? If we already have a sync button, won't creating a refresh button with same functionality be redundant?

**Comment by Rimjhim28** [comment]
@f4ww4z If this sounds reasonable to you could you please look at issues [AC-542](https://issues.openmrs.org/browse/AC-542), [AC-548](https://issues.openmrs.org/browse/AC-548), [AC-549](https://issues.openmrs.org/browse/AC-549) and make them ready for work if they are valid.

**Comment by f4ww4z** [comment]
@Rimjhim28 You are right, the sync button is already present at the Details tab. I think that it should be available on **all** the tabs though, so that users can see updated visits, diagnosis, etc. Can you file a new issue for this?

Meanwhile, PR LGTM!

**Comment by Rimjhim28** [comment]
Thank You @f4ww4z !
I have created [AC-550](https://issues.openmrs.org/projects/AC/issues/AC-550) for it.
Please review!

**Pull request merged**
