### PR TITLE
AC-591 Improved UI of login button and FragmentDialogue buttons

### PR DESCRIPTION
**Pull request by rishabh-997**
## Description of what I changed
I've modified the login_button_color.xml file to adapt it to changes in the background as well.
I've changed the fragment_dialog_layout.xml so that all the custom dialogues now gives a better visual appeal to the app.

## Issue I worked on

JIRA Issue: https://issues.openmrs.org/browse/AC-591

## Checklist: I completed these to help reviewers :)

- [x] My pull request only contains **ONE single commit**
(the number above, next to the 'Commits' tab is 1).

- [ ] I have **added tests** to cover my changes. (If you refactored
existing code that was well tested you do not have to add tests)

- [x] All new and existing **tests passed**.

- [x] My pull request is **based on the latest changes** of the master branch.

### CODE REVIEW

**Comment by ribhavsharma** [comment]
@rishabh-997 Can you please attach screenshots?

**Comment by rishabh-997** [comment]
> @rishabh-997 Can you please attach screenshots?

yeah, I've posted the images on JIRA issue at [link](https://issues.openmrs.org/browse/AC-591)

**Comment by ribhavsharma** [comment]
> > @rishabh-997 Can you please attach screenshots?
> 
> yeah, I've posted the images on JIRA issue at [link](https://issues.openmrs.org/browse/AC-591)

Hi rishabh, I checked out your screenshots :)
But the According to the Material guidelines, the button text shouldn't be italic. Can we replace these buttons with material buttons?

**Comment by f4ww4z** [comment]
>  But According to the Material guidelines, the button text shouldn't be italic. Can we replace these buttons with material buttons?

@rishabh-997 Did you see this? Also, for darker-colored button backgrounds, the text should be white. E.g. the `login` button should have white text with that green color background.

Please send the screenshots here in this PR.

**Comment by rishabh-997** [comment]
> > But According to the Material guidelines, the button text shouldn't be italic. Can we replace these buttons with material buttons?
> 
> @rishabh-997 Did you see this? Also, for darker-colored button backgrounds, the text should be white. E.g. the `login` button should have white text with that green color background.
> 
> Please send the screenshots here in this PR.

was engaged in kotlin migration, will update this today

**Comment by rishabh-997** [comment]
Done with the changes, here is the  screenshot:
image 1.jpeg?alt=media&token=00c4ba0a-819a-4fc4-a1e1-7ac4957a8f98)
image 2.jpeg?alt=media&token=4134d0c0-e815-4fa0-85ee-bdc4c606e27d)
image 3

**Comment by ribhavsharma** [comment]
can we use the ```<MaterialButton>``` tag instead of the default button?  It would not need much styling too. Check this out https://material.io/develop/android/components/material-button/

**Comment by rishabh-997** [comment]
> can we use the `<MaterialButton>` tag instead of the default button? It would not need much styling too. Check this out https://material.io/develop/android/components/material-button/

I have migrated buttons to Material Buttons but I think that change was not required as I still had to write all the boilerplate code. Nevertheless, Have a look at the PR now.

**Comment by ribhavsharma** [comment]
@rishabh-997 Please update the screenshots :)

**Comment by rishabh-997** [comment]
> @rishabh-997 Please update the screenshots :)

image

**Comment by ribhavsharma** [comment]
@rishabh-997 I guess there's an error in your code, because the buttons are not actually visible.

**Comment by rishabh-997** [comment]
> @rishabh-997 I guess there's an error in your code, because the buttons are not actually visible.

Exactly that's why I was not using material button as it overrides many functionalities... I tried using bordered style but it was worthless

**Comment by ribhavsharma** [comment]
@rishabh-997 let's see what @f4ww4z says about this, otherwise we won't have any option but ti rollback :/

**Comment by rishabh-997** [comment]
Any suggestions @f4ww4z  sir

**Comment by ribhavsharma** [comment]
@rishabh-997 try playing around with the elevation a bit? also, please keep the same text color for the two buttons to maintain consistency.

**Comment by f4ww4z** [comment]
> > @rishabh-997 Please update the screenshots :)
> 
> image

@rishabh-997 how about using the default button, with the background color the same as the appbar's color (dark green)? The text should be white of course. Right now it doesn't look like a button, and it won't be consistent with other buttons in the app.

> @rishabh-997 try playing around with the elevation a bit? also, please keep the same text color for the two buttons to maintain consistency.

The default `Button` should already have elevation I believe. Try using that @rishabh-997 . Login button looks good.

**Comment by ribhavsharma** [comment]
Please resolve merge conflicts :)

**Comment by rishabh-997** [comment]
Can't log in into the app due to down server past few hours... So here is direct design of how it will look
Image

**Comment by rishabh-997** [comment]
@f4ww4z  sir, I changed the background as per you requested... Please select one of them, I'll update the PR as per that...
try 1.jpeg?alt=media&token=f7d9bfac-e4a2-4308-992c-ebcf615a79cf)
try 2.jpeg?alt=media&token=15e300ed-652c-4614-b949-7249c45c603e)
try 3

**Comment by ribhavsharma** [comment]
Looks good Rishabh!

**Pull request merged**
