### PR TITLE
AC-498 Added Delete Image for Uploaded image

### PR DESCRIPTION
**Pull request by VANKINEENITAWRUN**
## Description of what I changed
Added an option to camera Dialog for Image Removal. As the Remove Photo option clicked change the Patientphoto to person_grey_icon Bitmap.

## Issue I worked on

JIRA Issue: https://issues.openmrs.org/browse/AC-498

## Checklist: I completed these to help reviewers :)

- [x] My pull request only contains **ONE single commit**
(the number above, next to the 'Commits' tab is 1).

- [ ] I have **added tests** to cover my changes. (If you refactored
existing code that was well tested you do not have to add tests)

- [x] All new and existing **tests passed**.

- [x] My pull request is **based on the latest changes** of the master branch.

### CODE REVIEW

**Comment by codepoet2017390** [comment]
Also i think it would be better if the patient image is deleted from the server side as well. Present fix just deletes the image on the users device but the patient image still persists in the database leading to inconsistency in the implementers database. As far as i know there is no speicific API for deleting an image but this can be dealt with using the existing update APIs and updating the image with a generic placeholder (as already existing by defalut).

**Comment by VANKINEENITAWRUN** [comment]
> Also i think it would be better if the patient image is deleted from the server side as well. Present fix just deletes the image on the users device but the patient image still persists in the database leading to inconsistency in the implementers database. As far as i know there is no speicific API for deleting an image but this can be dealt with using the existing update APIs and updating the image with a generic placeholder (as already existing by defalut).

**Comment by VANKINEENITAWRUN** [comment]
> but this can be dealt with using the existing update APIs and updating the image with a generic placeholder (as already existing by default).

Exactly that's what is done. when a user removes the image, a bitmap of `R.drawable.ic_person_grey_500_48dp.png` gets updated as a patient profile. so the previous profile gets overwritten.

**Comment by codepoet2017390** [comment]
Then just sync patient data.

**Comment by codepoet2017390** [comment]
Ok just saw this is a part of the update patient activity. Looks good

**Comment by f4ww4z** [comment]
@VANKINEENITAWRUN If you fix the merge conflict, I'm happy to merge this.

**Pull request merged**
