### PR TITLE
AC-807 fixed the reverse flipping bug

### PR DESCRIPTION
**Pull request by LuGO0**
## Description of what I changed
fixed the reverse flipping bug by removing static modifier on the flag variable

## Issue I worked on

JIRA Issue: https://issues.openmrs.org/browse/AC-807

## Checklist: I completed these to help reviewers :)

- [x] My pull request only contains **ONE single commit**
(the number above, next to the 'Commits' tab is 1).

- [ ] I have **added tests** to cover my changes. (If you refactored
existing code that was well tested you do not have to add tests)

- [x] All new and existing **tests passed**.

- [x] My pull request is **based on the latest changes** of the master branch.

### CODE REVIEW

**Comment by LuGO0** [comment]
@f4ww4z please review!!

**Comment by LuGO0** [comment]
Sure @rishabh-997 I was trying to make a gif will do this !!

**Comment by LuGO0** [comment]
> Sure @rishabh-997 I was trying to make a gif will do this !!

Actually thr vid was a bit long it dint support gif

**Comment by f4ww4z** [comment]
@LuGO0 Make sure your PR commit and title matches the JIRA issue's next time.

**Pull request merged**
