### PR TITLE
AC-894 Migrate Service package to Kotlin

### PR DESCRIPTION
**Pull request by avinash14022002**
## Description of what I changed
Converted Service package to Kotlin

## Issue I worked on
JIRA Issue: https://issues.openmrs.org/browse/AC-891

## Checklist: I completed these to help reviewers :)
- [ ] My pull request only contains **ONE single commit**
(the number above, next to the 'Commits' tab is 1).

- [x] I have **added tests** to cover my changes. (If you refactored
existing code that was well tested you do not have to add tests)

- [x] All new and existing **tests passed**.
- [x] My pull request is **based on the latest changes** of the master branch.

### CODE REVIEW

**Comment by shivamsawlani02** [comment]
@avinash14022002  Please follow the contribution guidelines. Attach the issue ticket number to the pull request title and the commit messages. You can refer to the guidelines by heading over to this link [Contribution Guidelines](https://github.com/openmrs/openmrs-contrib-android-client/blob/master/CONTRIBUTING.md).
Also, you can start working on an issue only when it is approved by a mentor.

**Comment by avinash14022002** [comment]
Sorry @shivamsawlani02 sir,
I was not knowing about it

Sir,
are you a mentor?

**Comment by shivamsawlani02** [comment]
> Sorry @shivamsawlani02 sir,
> I was not knowing about it
> 
> Sir,
> are you a mentor?

No bro. I am also a student.

**Comment by rishabh-997** [comment]
Wait for the issue to get ready, as mentioned, read every line of guideline carefully and thoroughly.

**Pull request closed without merging**
