### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by Vsareen0**
## Issue I worked on

JIRA Issue: https://issues.openmrs.org/browse/AC-

## Checklist: I completed these to help reviewers :)

- [x] My pull request only contains **ONE single commit**
(the number above, next to the 'Commits' tab is 1).

- [x] I have **added tests** to cover my changes. (If you refactored
existing code that was well tested you do not have to add tests)

- [x] All new and existing **tests passed**.

- [x] My pull request is **based on the latest changes** of the master branch.

### CODE REVIEW

**Comment by deepak140596** [comment]
@Vsareen0 , please follow Pull Requests [guidelines](https://wiki.openmrs.org/display/docs/Pull+Request+Tips). 
If the issue doesn't exists on JIRA, create it and wait for the moderator to make the issue ready for work.

**Comment by f4ww4z** [comment]
@Vsareen0 Did you see the comments above? Please close this pull request and file an issue in JIRA first.

**Comment by Kapil706** [comment]
Hello, Create an Issue named Updating Readme file from the JIRA ticket manager for OpenMRS
Need help 
Revert Back

**Comment by f4ww4z** [comment]
Closing due to inactivity. @Vsareen0 You can create an issue in JIRA first regarding this.

**Comment by Vsareen0** [comment]
hey I just saw your comments now, I am really sorry for such a delay response and thanks for providing the guidelines and closing this on my behalf.

**Pull request closed without merging**
