### PR TITLE
AC-802: Small UI fix for contact Us screen

### PR DESCRIPTION
**Pull request by LuGO0**
## Description of what I changed
1. added required elevation
2. removed or text
3. snackbar doesnt hide any text now

## Issue I worked on

JIRA Issue: https://issues.openmrs.org/browse/AC-802

## Checklist: I completed these to help reviewers :)

- [x] My pull request only contains **ONE single commit**
(the number above, next to the 'Commits' tab is 1).

- [ ] I have **added tests** to cover my changes. (If you refactored
existing code that was well tested you do not have to add tests)

- [x] All new and existing **tests passed**.

- [x] My pull request is **based on the latest changes** of the master branch.

### CODE REVIEW

**Comment by LuGO0** [comment]
the UI after change @f4ww4z @rishabh-997  please review
WhatsApp Image 2020-07-07 at 3 04 34 AM

**Comment by rishabh-997** [comment]
> The UI after change @f4ww4z @rishabh-997 please review
> 
> WhatsApp Image 2020-07-07 at 3 04 34 AM

I feel **OR** looks good. Can coordinator layout help pushing the layout above when snackbar pops up ? Else the PR is fine.

**Comment by LuGO0** [comment]
> I feel **OR** looks good. Can coordinator layout help pushing the layout above when snackbar pops up ? Else the PR is fine.

@rishabh yes I tried that as well but the scroll view gets chopped off at the beginning so it again dosent looks good so I decided to remove "OR"

**Comment by f4ww4z** [comment]
@LuGO0 Still keep the 'OR', but lower the image to about 60% of the screen width or until everything fits on the screen without needing to scroll.

Also change the PR title to the JIRA issue title. See our PR tips

**Comment by LuGO0** [comment]
> @LuGO0 Still keep the 'OR', but lower the image to about 60% of the screen width or until everything fits on the screen without needing to scroll.
> 
> Also change the PR title to the JIRA issue title. See our PR tips

okay @f4ww4z  I would do this

**Comment by f4ww4z** [comment]
@LuGO0 Did you forget the ticket number?

**Pull request merged**
