### PR TITLE
AC 506 - Create toasts when toggling the syncbutton

### PR DESCRIPTION
**Pull request by HelioStrike**
# Create Toast when connecting to/disconnecting from server

## Description of what I changed

Imported Toast in ACBaseActivity.java and creating a toast whenever the syncbutton(the cloud icon on the toolbar) is tapped, notifying the user that he is connecting to/disconnecting from the server.  

Added 2 entires to strings.xml to avoid hard coding.

## Issue I worked on

JIRA Issue: https://issues.openmrs.org/browse/AC-506

## Checklist: I completed these to help reviewers :)

-  [x] My pull request only contains **ONE single commit**
(the number above, next to the 'Commits' tab is 1).

- [ ] I have **added tests** to cover my changes. (If you refactored
existing code that was well tested you do not have to add tests)

- [x] All new and existing **tests passed**.

-  [x] My pull request is **based on the latest changes** of the master branch.

### CODE REVIEW

**Comment by f4ww4z** [comment]
@HelioStrike You might have rebased too many commits. My suggestion is to **copy your changes to an editor**,  run `git reset --hard origin/master` and then make the desired changes. Thanks.

**Comment by HelioStrike** [comment]
Yea... sorry about that. Its fixed now, please have another look. :)

**Comment by HelioStrike** [comment]
Aye! I changed the code to use ToastUtil.showShortText.

About the travis build failure, I noticed a comment in PR #463 saying that its due to existing lint errors.

**Comment by f4ww4z** [comment]
Thanks @HelioStrike , just one last todo. Can you a gif / screen recording that is showing this feature? Attach in in the JIRA issue. Also, rename your commit to the format mentioned in https://wiki.openmrs.org/display/docs/Pull+Request+Tips .

**Comment by HelioStrike** [comment]
I couldn't find anything about renaming commits in that link, not sure if I'm missing something. I made the attachment though. :D

**Comment by f4ww4z** [comment]
Did you see the '**Reference the ticket**' section?

**Comment by HelioStrike** [comment]
I missed that, thanks for pointing me to it! The commit is renamed.

**Pull request merged**
