### PR TITLE
AC-653: README.md - replace 'other' to 'Tabs and Indents'

### PR DESCRIPTION
**Pull request by vish198910**
…in the Development section of the file README.md
AC-653 Correcting the README.md file

## Description of what I changed

I have changed the tab name from "other" to "Tabs and Indents" in the development section of file
## Issue I worked on

JIRA Issue: https://issues.openmrs.org/browse/AC-653

## Checklist: I completed these to help reviewers :)

- [ x] My pull request only contains **ONE single commit**
(the number above, next to the 'Commits' tab is 1).

- [ ] I have **added tests** to cover my changes. (If you refactored
existing code that was well tested you do not have to add tests)

- [ x] All new and existing **tests passed**.

- [x ] My pull request is **based on the latest changes** of the master branch.

### CODE REVIEW

**Comment by ribhavsharma** [comment]
Good Work!

**Comment by vish198910** [comment]
Thanks

**Comment by f4ww4z** [comment]
@vish198910 That is not a valid PR title.

**Comment by vish198910** [comment]
Okay, so what should be title.

**Pull request merged**
