### PR TITLE
AC-347:Comments for the test class

### PR DESCRIPTION
**Pull request by suthagar23**
It hasn't any more comments to continue the test case class. So I have updated some test case comments to who new to the testclass development. I will continue to make some comments briefly.

### CODE REVIEW

**Comment by suthagar23** [comment]
I didn't make a lot of comments at there, but I will continue to make the test class with better comments. It will easy to identify by the new entries

**Comment by shivtej1505** [comment]
@suthagar23, I suggest you to report any issue you find and then wait till it is marked as `ready to work` . After then you can claim it and start working on it.
BTW, I saw the comments added by you but I personally feel that anyone can understand code without them also because functions and variables names are choosen in such a way.
 @tmarzeion , @AvijitGhosh82 could you please your views about it.

**Comment by suthagar23** [comment]
That's Good. anyway this is my startup, so I will make further changes asap.

**Comment by dkayiwa** [comment]
@suthagar23 did you get to make further changes? 😊

**Comment by dkayiwa** [comment]
@suthagar23 are you still working on this?

**Comment by AvijitGhosh82** [comment]
Please finish this :) Will be really helpful once merged.

**Comment by dkayiwa** [comment]
@suthagar23 are you still working on this? Or should i just close it?

**Pull request closed without merging**
