### PR TITLE
AC-965 Converted FormDisplay Layout

### PR DESCRIPTION
**Pull request by Rohit-2602**
## Issue I worked on

JIRA Issue: https://issues.openmrs.org/browse/AC-965

## Checklist: I completed these to help reviewers :)

- [x] My pull request only contains **ONE single commit**
(the number above, next to the 'Commits' tab is 1).

- [ ] I have **added tests** to cover my changes. (If you refactored
existing code that was well tested you do not have to add tests)

- [x] All new and existing **tests passed**.

- [x] My pull request is **based on the latest changes** of the master branch.

### CODE REVIEW

**Comment by shivamsawlani02** [comment]
@Rohit-2602 please attach JIRA ticket ID to the PR title and the commit message.

**Comment by Rohit-2602** [comment]
Done

**Comment by HerbertYiga** [comment]
@Rohit-2602  add a ticket id to your commit message

**Comment by LuGO0** [comment]
Always attach screenshots of visual changes 👍🏼

**Comment by Rohit-2602** [comment]
After Changes
Before Changes

**Comment by Rohit-2602** [comment]
@LuGO0 done

**Comment by shivamsawlani02** [comment]
What did you change in the last two commits? The second commit is similar to the first one and the third commit is useless as it has no changes. Also, the Travis Build failed. Please look into that.

**Comment by Rohit-2602** [comment]
I just change the commit message, but now I created a new PR.

**Comment by LuGO0** [comment]
@Rohit-2602 will close this for inactivity and Issue will be up for taking again if you are not working on this.

**Comment by Rohit-2602** [comment]
@LuGO0 Issue is solved in another PR, I wanna ask to close this PR??

**Pull request closed without merging**
