### PR TITLE
AC-980 Migration-from-java-to-kotlin

### PR DESCRIPTION
**Pull request by farhazulMullick**
AC- Migration to kotlin

## Issue I worked on

JIRA Issue: https://issues.openmrs.org/browse/AC-980

I Migrated 
1. OpenMrsInflater.java
2. UserService.java 
3. SyncStateReciever.java
4. PatientService.java
5. EncounterService.java
6. FormListService.java
7. AuthorizationManager.java

to Kotlin 

## Checklist: I completed these to help reviewers :)

- [ ] My pull request only contains **ONE single commit**
(the number above, next to the 'Commits' tab is 1).

- [ ] I have **added tests** to cover my changes. (If you refactored
existing code that was well tested you do not have to add tests)

- [x] All new and existing **tests passed**.

- [x] My pull request is **based on the latest changes** of the master branch.

### CODE REVIEW

**Comment by shivamsawlani02** [comment]
@farhazulMullick you have to create an issue in JIRA first and then only you can start working on it. You can have a look at the [Contribution Guidelines](https://github.com/openmrs/openmrs-contrib-android-client/blob/master/CONTRIBUTING.md) here.

**Comment by HerbertYiga** [comment]
> https://issues.openmrs.org/browse/AC-

Thanks @farhazulMullick  could you also correct this ticket id and add a ticket title to your ticket too

**Comment by farhazulMullick** [comment]
> 
> 
> @farhazulMullick you have to create an issue in JIRA first and then only you can start working on it. You can have a look at the [Contribution Guidelines](https://github.com/openmrs/openmrs-contrib-android-client/blob/master/CONTRIBUTING.md) here.

I went through CONTRIBUTING.md file created openMRS ID but i could'nt end up with creating a new issue token on  migration existing code to kotlin 
If you can the please open an issue on migration to kotlin and Converting AsyncTask to Coroutines in project files

I will be happy to work on that

**Comment by shivamsawlani02** [comment]
@farhazulMullick you can follow the steps in this [link](https://wiki.openmrs.org/display/docs/How+to+get+access+to+issues.openmrs.org) to request access to JIRA. Once you get the access, you will be able to create issues.

**Comment by farhazulMullick** [comment]
@shivamsawlani02 thank you very much i could rise an issue [AC - 980]. Now should i edit the jira issue link above or should i again make pull request with latest changes.

**Comment by LuGO0** [comment]
The Issue is not ready yet.

**Pull request closed without merging**
