### PR TITLE
AC-878 changes to the Allergy info UI

### PR DESCRIPTION
**Pull request by K1RA-16**
## Description of what I changed
1) The options of "choose a category" and "Severity " were quite close,  added space to make them seperated.
2) No regularity in the selected option between "choose a category" and "Severity " changed them to have the same colour.

## Issue I worked on
https://issues.openmrs.org/browse/AC-878
(saw the issue not being worked on for quite some time so i assigned it to myself)

## Checklist: I completed these to help reviewers :)

- [x] My pull request only contains **ONE single commit**

- [ ] I have **added tests** to cover my changes. (If you refactored
existing code that was well tested you do not have to add tests)

- [x] All new and existing **tests passed**.

- [x] My pull request is **based on the latest changes** of the master branch.

### CODE REVIEW

**Comment by K1RA-16** [comment]
@jwnasambu @LuGO0 please review this.

**Comment by LuGO0** [comment]
@K1RA-16 please attach screenshots for visual changes before and after its easier to review that way.

**Comment by K1RA-16** [comment]
unchanged

Screenshot_20210213-213341

changed

Screenshot_1627807456

**Comment by K1RA-16** [comment]
@LuGO0 please review this :)

**Comment by K1RA-16** [comment]
@LuGO0 can you please also change the status to ready for work in 
AC-690 
ive made the required changes, i'll generate a PR as soon as you change the status

**Comment by LuGO0** [comment]
LGTM !!

**Pull request merged**
