### PR TITLE
AC-864 : Made some changes in workflow

### PR DESCRIPTION
**Pull request by LuGO0**
## Description of what I changed

1. Incase device is offline we shouldnt display null rather than we should display what is there in the database with a log that offline sync failed.
2. while inserting the server data in our offline db we must not replace rather ignore if conflicts occur since it might have been updated offine and it will get updated to the server through the worker in a while.

## Issue I worked on

JIRA Issue: https://issues.openmrs.org/browse/AC-864

## Checklist: I completed these to help reviewers :)

- [x] My pull request only contains **ONE single commit**
(the number above, next to the 'Commits' tab is 1).

- [ ] I have **added tests** to cover my changes. (If you refactored
existing code that was well tested you do not have to add tests)

- [x] All new and existing **tests passed**.

- [x] My pull request is **based on the latest changes** of the master branch.

### CODE REVIEW

**Comment by LuGO0** [comment]
@rishabh-997 I want views on this one is it good to merge or it needs some more work?

**Review by rishabh-997 — COMMENTED** [review]
Can you add a small video reflecting your changes

**Comment by LuGO0** [comment]
@rishabh-997 its still is normal workflow, just when the device is offline we dont get to see the `no data to display`, rather we get to see the locally saved providers.

**Review by rishabh-997 — APPROVED** [review]
yeah, LGTM

**Pull request merged**
