### PR TITLE
AC - 166

### PR DESCRIPTION
**Pull request by brainbreaker**
Upgraded all the ListViews to RecyclerViews

### CODE REVIEW

**Comment by brainbreaker** [comment]
@AvijitGhosh82 Why there is this merge conflict?

**Comment by AvijitGhosh82** [comment]
@brainbreaker Pull from master once and see. You can then fix the merge conflicts.

**Comment by brainbreaker** [comment]
@AvijitGhosh82 I pulled from the master and merged master in my issue branch AC-166. Then, I squashed the merge commit and previous commit, wrote new commit message and pushed. Still not resolved.

**Comment by brainbreaker** [comment]
# Closed due to merge conflicts. Created new PR(#149)

**Pull request closed without merging**
