### PR TITLE
AC-302: Lint adjustment - Performance

### PR DESCRIPTION
**Pull request by adhi1419**
Fixed all (6) "Useless Parent Layout" lint warnings

### CODE REVIEW

**Comment by adhi1419** [comment]
Correction - All commits belong to AC-302 and not AC-306

**Comment by AvijitGhosh82** [comment]
Squash your commits please.

**Comment by AvijitGhosh82** [comment]
1. Squash related commits
2. Rename your commits. Use rebase -i to do so.

**Comment by AvijitGhosh82** [comment]
These still aren't squashed. Combine them into a single commit.

**Comment by adhi1419** [comment]
@AvijitGhosh82 check now.

**Comment by AvijitGhosh82** [comment]
Hey @adhi1419 , thanks for the PR! There was a similar PR for the same issue before your's, so I merged that one to be fair. You should pull the changes from upstream now and check if you have anything else to add. Thanks!

**Pull request closed without merging**
