### PR TITLE
AC-481: Fixed build.gradle file to fix build issues

### PR DESCRIPTION
**Pull request by anuar2k**
## Description of what I changed
I have fixed a build issue (which I reported before, in the link below).
This PR fixes a bug in gradle, which makes it impossible to import and build the project.
**All existing tests passed.**
## Issue I worked on

https://issues.openmrs.org/browse/AC-481

### CODE REVIEW

**Comment by dkayiwa** [comment]
@anuar2k did you take a look at this? https://wiki.openmrs.org/display/docs/Pull+Request+Tips

**Comment by anuar2k** [comment]
@dkayiwa I've updated the description a bit. This PR meets all requirements listed on the wiki page now.

**Comment by dkayiwa** [comment]
@anuar2k can you explain what is accomplished by moving the google method to the top?

**Comment by anuar2k** [comment]
@dkayiwa This is a fix to unresolved issue (causing the build to fail because of unresolved dependencies when importing the project, described in JIRA ticket referenced above) with Android Studio reported here: https://issuetracker.google.com/issues/80362794 I've tried to find the explanation why `google()` has to precede `jcenter()`, but I failed to do so. There is several StackOverflow threads referencing this issue, all suggesting the fix I've commited above.

Reference:
https://stackoverflow.com/a/50758769/8998560
https://stackoverflow.com/a/50790391/8998560
https://stackoverflow.com/a/50567130/8998560
https://stackoverflow.com/a/50790391/8998560

**Comment by anuar2k** [comment]
@f4ww4z updated :)

**Comment by dkayiwa** [comment]
@f4ww4z you should now be having write privileges to this repository, and hence in position to merge those pull requests that you see fit. 😊

**Comment by dkayiwa** [comment]
@f4ww4z you also have permissions to close the corresponding JIRA tickets as you see fit. 👍

**Comment by f4ww4z** [comment]
Thanks @dkayiwa ! I am excited to see lots more contributions to this project 👍 .

**Comment by dkayiwa** [comment]
@f4ww4z we are also very excited to see you take on a leadership role to this project! 😊

**Pull request merged**
