### PR TITLE
AC - 848: Updated and Fixed Typos

### PR DESCRIPTION
**Pull request by the-rebooted-coder**
## Description of what I changed
AC - 848: Updated and Fixed Typos

## Issue I worked on
JIRA Issue: https://issues.openmrs.org/browse/AC-848

## Checklist: I completed these to help reviewers :)
- [x] My pull request only contains **ONE single commit**
(the number above, next to the 'Commits' tab is 1).

- [x] I have **added tests** to cover my changes. (If you refactored
existing code that was well tested you do not have to add tests)

- [x] All new and existing **tests passed**.

- [x] My pull request is **based on the latest changes** of the master branch.

### CODE REVIEW

**Comment by shivamsawlani02** [comment]
@the-rebooted-coder this issue contains other changes also which need to be addressed.

**Comment by HerbertYiga** [comment]
@the-rebooted-coder  could you add a ticket Id too to your commit message!

**Comment by the-rebooted-coder** [comment]
> @the-rebooted-coder this issue contains other changes also which need to be addressed.

Yes sir, actually I couldn't find a particular issue ID for a small typo, so I clubbed it with this PR

**Comment by the-rebooted-coder** [comment]
> @the-rebooted-coder could you add a ticket Id too to your commit message!

Sure!
Could you please guide me on how to get a ticket?
I guess it has to be taken from JIRA but, I am tad new here so help would be appreciated :)

**Comment by HerbertYiga** [comment]
> > @the-rebooted-coder could you add a ticket Id too to your commit message!
> 
> Sure!
> Could you please guide me on how to get a ticket?
> I guess it has to be taken from JIRA but, I am tad new here so help would be appreciated :)

it is this  (AC - 848)so the best commit message would have been->  AC - 848:Updated and Fixed Typos

**Comment by the-rebooted-coder** [comment]
> > > @the-rebooted-coder could you add a ticket Id too to your commit message!
> > 
> > 
> > Sure!
> > Could you please guide me on how to get a ticket?
> > I guess it has to be taken from JIRA but, I am tad new here so help would be appreciated :)
> 
> it is this (AC - 848)so the best commit message would have been-> AC - 848:Updated and Fixed Typos

done!

**Comment by HerbertYiga** [comment]
> > > > @the-rebooted-coder could you add a ticket Id too to your commit message!
> > > 
> > > 
> > > Sure!
> > > Could you please guide me on how to get a ticket?
> > > I guess it has to be taken from JIRA but, I am tad new here so help would be appreciated :)
> > 
> > 
> > it is this (AC - 848)so the best commit message would have been-> AC - 848:Updated and Fixed Typos
> 
> done!

check properly your commit message not the ticket Title

**Comment by rishabh-997** [comment]
> other changes also which need to be addressed

.

**Pull request closed without merging**
