### PR TITLE
Reallocated MVP to Dashboard

### PR DESCRIPTION
**Pull request by amtheshubham**
## Issue I worked on

JIRA Issue: https://issues.openmrs.org/browse/AC-884

## Checklist: I completed these to help reviewers :)

- [x] My pull request only contains **ONE single commit**

- [ ] No new tests required

- [x] All existing **tests passed**.

- [x] My pull request is **based on the latest changes** of the master branch.

### CODE REVIEW

**Comment by amtheshubham** [comment]
**The App is working absolutely fine after this:**

https://user-images.githubusercontent.com/52814595/109431027-68c6b480-7a2a-11eb-9375-bb24770d6c26.mp4

**Comment by amtheshubham** [comment]
@LuGO0 Review please

**Comment by HerbertYiga** [comment]
you can also add a ticket id to your commit as recommended here,https://wiki.openmrs.org/display/docs/Pull+Request+Tips

**Comment by amtheshubham** [comment]
> you can also add a ticket id to your commit as recommended here,https://wiki.openmrs.org/display/docs/Pull+Request+Tips

oops :P **Done**!

**Comment by amtheshubham** [comment]
@rishabh-997 This one is ready to be merged

**Review by rishabh-997 — APPROVED** [review]
LGTM

**Pull request merged**
