### PR TITLE
AC-839 Updated UI for form list card view

### PR DESCRIPTION
**Pull request by rishabh-997**
## Issue I worked on

JIRA Issue: https://issues.openmrs.org/browse/AC-839

## Checklist: I completed these to help reviewers :)

- [x] My pull request only contains **ONE single commit**
(the number above, next to the 'Commits' tab is 1).

- [ ] I have **added tests** to cover my changes. (If you refactored
existing code that was well tested you do not have to add tests)

- [x] All new and existing **tests passed**.

- [x] My pull request is **based on the latest changes** of the master branch.

### CODE REVIEW

**Comment by rishabh-997** [comment]
> cant we just remove it all together

Do you mean something like this??? Both looks good to me. Thoughts @f4ww4z sir
Group 63 (1)

**Comment by LuGO0** [comment]
> > cant we just remove it all together
> 
> Do you mean something like this??? Both looks good to me. Thoughts @f4ww4z sir
> Group 63 (2)

yes actually since its quite a low level detail and I think its unnecessary to put up here

**Comment by f4ww4z** [comment]
@rishabh-997 I agree with @LuGO0 , remove the DOB. Also decrease the margin between the cards. Can you also post a screenshot for dark mode when it's done?

**Comment by rishabh-997** [comment]
> Can you also post a screenshot for dark mode when it's done?

WhatsApp Image 2020-08-26 at 12 26 22 AM

**Review by LuGO0 — APPROVED** [review]

**Review by f4ww4z — APPROVED** [review]
LGTM @rishabh-997

**Pull request merged**
