### PR TITLE
AC-1029: Add ViewModel & LivaData dependencies

### PR DESCRIPTION
**Pull request by amrsalah3**
## Description of what I changed

I've added ViewModel & LiveData dependencies. **_This PR also combines the previous PR into it (945) (AC-1028)._**
## Issue I worked on

JIRA Issue: https://issues.openmrs.org/browse/AC-1029

## Checklist: I completed these to help reviewers :)

- [x] My pull request only contains **ONE single commit**
(the number above, next to the 'Commits' tab is 1).

- [ ] I have **added tests** to cover my changes. (If you refactored
existing code that was well tested you do not have to add tests)

- [x] All new and existing **tests passed**.

- [x] My pull request is **based on the latest changes** of the master branch.

### CODE REVIEW

**Comment by amrsalah3** [comment]
@Rohit-2602 Added empty lines at the end of all files here, too.

**Review by Rohit-2602 — APPROVED** [review]

**Comment by kdaud** [comment]
@Rohit-2602 @amrsalah3  I have skimmed through this PR and noticed there are changes similar to what is in pull/945. How do you see if we first merge that PR then have this one debased to master?

**Comment by amrsalah3** [comment]
> @Rohit-2602 @amrsalah3 I have skimmed through this PR and noticed there are changes similar to what is in pull/945. How do you see if we first merge that PR then have this one debased to master?

If you mean rebasing this PR on top of the master after merging the previous one, it seems good to me.

**Comment by amrsalah3** [comment]
@kdaud 
Could this PR be rebased or merged onto master from here after merging AC-1028? Or should I fetch and rebase locally?

**Pull request merged**
