### PR TITLE
AC-984 : Delete Operation Offline Support for Allergy Respository.

### PR DESCRIPTION
**Pull request by LuGO0**
## Description of what I changed

1. for updation and addition we cant have offline support since they need to fetch concepts on the fly to create or update allergies.
2. for deletion we can have offline support using workers since no such requirement exists.

## Issue I worked on

JIRA Issue: https://issues.openmrs.org/browse/AC-984

## Checklist: I completed these to help reviewers :)

- [ ] My pull request only contains **ONE single commit**
(the number above, next to the 'Commits' tab is 1).

- [ ] I have **added tests** to cover my changes. (If you refactored
existing code that was well tested you do not have to add tests)

- [ ] All new and existing **tests passed**.

- [ ] My pull request is **based on the latest changes** of the master branch.

### CODE REVIEW

**Comment by LuGO0** [comment]
Hi @rishabh-997, I wanted to ask if there is a way to somehow reconstruct allergenCreate from AllergyEntity? That would become easier to enable offline addition and deletion for allergies as well !!

**Comment by LuGO0** [comment]
Hi @rishabh-997 I added AllergyCreate to the entity list and save it offline and then used workers to enable offline functionality for allergyCreation.

**Comment by LuGO0** [comment]
Hi @rishabh-997 please review !!

**Review by rishabh-997 — APPROVED** [review]
LGTM...

**Pull request merged**
