### PR TITLE
AC-965 Converted FormDisplay Layout

### PR DESCRIPTION
**Pull request by Rohit-2602**
## Issue I worked on

JIRA Issue: https://issues.openmrs.org/browse/AC-965

## Checklist: I completed these to help reviewers :)

- [x] My pull request only contains **ONE single commit**
(the number above, next to the 'Commits' tab is 1).

- [ ] I have **added tests** to cover my changes. (If you refactored
existing code that was well tested you do not have to add tests)

- [x] All new and existing **tests passed**.

- [x] My pull request is **based on the latest changes** of the master branch.

### CODE REVIEW

**Comment by Rohit-2602** [comment]
After Changes
Before Changes

**Comment by Rohit-2602** [comment]
@LuGO0 should I close the previous PR??

**Comment by HerbertYiga** [comment]
@Rohit-2602   can you point me to the screen shot of before and after your changes!

**Comment by Rohit-2602** [comment]
@HerbertYiga the above is after changes and the lower one is before changes.

**Comment by LuGO0** [comment]
The Issue is not ready yet

**Pull request closed without merging**
