### PR TITLE
AC-1010: Added ScrollView in activity_about.xml file

### PR DESCRIPTION
**Pull request by Anshul-9923**
AC-1010: Added ScrollView in activity_about.xml file

 Description of what I changed
I have added ScrollView in the activty_about.xml file to resolve the issue that the About Page is not scrollable in Landscape mode due to which the whole content of the About Page is not visible to the user. After making changes as mentioned above now the About Page is scrollable in landscape mode.

Issue:-
https://issues.openmrs.org/browse/AC-1010
About Page is not scrollable in the Landscape mode of the Openmrs Client application.

## Checklist: I completed these to help reviewers :)

- [x] My pull request only contains **ONE single commit**
(the number above, next to the 'Commits' tab is 1).

- [ ] I have **added tests** to cover my changes. (If you refactored
existing code that was well tested you do not have to add tests)

- [ ] All new and existing **tests passed**.

- [x] My pull request is **based on the latest changes** of the master branch.

### CODE REVIEW

**Comment by Anshul-9923** [comment]
@LuGO0 Please review my PR.

**Comment by LuGO0** [comment]
> @LuGO0 Please review my PR.

Please go through the contribution guidelines first. It will help you grt familiar with the workflow and in making meaning ful comtributions https://wiki.openmrs.org/plugins/servlet/mobile?contentId=60785449#content/view/60785449

**Comment by jwnasambu** [comment]
@Anshul-9923  this is a good beginning just to add on @LuGO0 comment kindly ensure the `issue` and the `description` of what you  worked on is well stated.  What do think if we had this above ?

**Description of what I changed:**
I have added ScrollView in the activity_about.xml file which is responsible for the About Page of the app. After changing it I can easily scroll the About page in Landscape Mode.

Issue worked on:
 https://issues.openmrs.org/browse/AC-989

**Comment by Anshul-9923** [comment]
@LuGO0 I have gone through the contribution guidelines and have requested code review on AC-989 in the Jira issue tracker.
@jwnasambu I have edited the description and issue of my PR.

**Comment by Anshul-9923** [comment]
@LuGO0 If my PR resolves the described issue please merge it to the master branch of the project.

**Comment by Anshul-9923** [comment]
@LuGO0 @jwnasambu I had created the PR for AC-989 but now Rohit Sharma made it as a subtask AC-1010. I have edited my PR to the solution of issue AC-1010. So, please kindly merge it to the master branch after reviewing my code.

**Comment by LuGO0** [comment]
please, exclude unecessary files from the PR.

**Comment by Anshul-9923** [comment]
@LuGO0 I have excluded unnecessary files from PR only one file has been changed to resolve the issue.

**Pull request merged**
