### PR TITLE
AC-648 Dashboard now responds to change in app theme

### PR DESCRIPTION
**Pull request by rishabh-997**
## Description of what I changed
I had to rectify following three bugs:
1. Firstly updated materials dependency to incoporate dayNight theme
2. Secondly, **updated and reverted** changed in PR #648 because of which, half of the activities lost their action bar and dark mode feature lost its functionality. :(
3. called setupTheme() in onResume of ACBaseActivity which is common for all activities 

## Issue I worked on

JIRA Issue: https://issues.openmrs.org/browse/AC-648

## Checklist: I completed these to help reviewers :)

- [x] My pull request only contains **ONE single commit**
(the number above, next to the 'Commits' tab is 1).

- [ ] I have **added tests** to cover my changes. (If you refactored
existing code that was well tested you do not have to add tests)

- [x] All new and existing **tests passed**.

- [x] My pull request is **based on the latest changes** of the master branch.

### CODE REVIEW

**Comment by rishabh-997** [comment]
Updated the PR !...

**Comment by rishabh-997** [comment]
@fawwaz sir, can you merge hindi version first, so i can nake changes when updating language too

**Comment by fawwaz** [comment]
I bet you are tagging wrong person

**Comment by rishabh-997** [comment]
> I bet you are tagging wrong person

my bard 😅... @f4ww4z sir

**Comment by rishabh-997** [comment]
I've also changed the splash screen to adapt to dark mode and also updated its UI which was a bit irritating previously... Attaching screenshots
Splash Screen
DashBoard

**Comment by rishabh-997** [comment]
@f4ww4z  sir  please review this PR because it solves the problem of hidden action bars which contains many functionalities and people are creating issues to add those functionalities...

**Comment by rishabh-997** [comment]
Reviews @fawwaz sir, this issue is a blocker due to the absence of action bar throughout the app...

**Pull request merged**
