### PR TITLE
Adds app demo

### PR DESCRIPTION
**Pull request by DefCon-007**
Below are the screenshots 

screenshot_1500109260
screenshot_1500109158
screenshot_1500109214
screenshot_1500109219

### CODE REVIEW

**Comment by AvijitGhosh82** [comment]
Use buttons for 'Next' and 'Close'. That is, these should look like buttons and not text. 

Also, have showcase in the inner screens as well, at least the first level screens.

**Comment by AvijitGhosh82** [comment]
Also add issue number and JIRA link.

**Comment by DefCon-007** [comment]
I have made the necessary changes, will update the screenshots once the login problem is resolved.

**Comment by DefCon-007** [comment]
Following are the screenshots.
screenshot_1501141479
screenshot_1501141482
screenshot_1501141486
screenshot_1501141489

**Pull request merged**
