### PR TITLE
AC-833 NPE fixed at PatientRepository due to patientIdentifierService Omission

### PR DESCRIPTION
**Pull request by LuGO0**
1. Reverted to patientIdentifierService class, Issue discussed here https://github.com/openmrs/openmrs-contrib-android-client/pull/847/files#r583491024

## Issue I worked on

JIRA Issue: https://issues.openmrs.org/browse/AC-833

## Checklist: I completed these to help reviewers :)

- [x] My pull request only contains **ONE single commit**
(the number above, next to the 'Commits' tab is 1).

- [x] I have **added tests** to cover my changes. (If you refactored
existing code that was well tested you do not have to add tests)

- [x] All new and existing **tests passed**.

- [x] My pull request is **based on the latest changes** of the master branch.

### CODE REVIEW

**Comment by LuGO0** [comment]
@rishabh-997 please review and merge

**Comment by amtheshubham** [comment]
@LuGO0 Please check by registering an example patient and then see the patient in **Find Patients** activity. Check if the Patient id is not null.

**Comment by rishabh-997** [comment]
> @LuGO0 Please check by registering an example patient and then see the patient in **Find Patients** activity. Check if the Patient id is not null.

What was the outcome ? @LuGO0

**Review by rishabh-997 — APPROVED** [review]

**Comment by LuGO0** [comment]
yes @rishabh-997 it works as expected.

**Pull request merged**
