### PR TITLE
Added Forget Password Option

### PR DESCRIPTION
**Pull request by Jeetanshu**
## Issue I worked on

JIRA Issue: https://issues.openmrs.org/browse/AC-

## Checklist: I completed these to help reviewers :)

- [x] My pull request only contains **ONE single commit**
(the number above, next to the 'Commits' tab is 1).

- [x] I have **added tests** to cover my changes. (If you refactored
existing code that was well tested you do not have to add tests)

- [x] All new and existing **tests passed**.

- [x] My pull request is **based on the latest changes** of the master branch.

### CODE REVIEW

**Comment by Jeetanshu** [comment]
I have added 'Forgot Password?' option in the LogIn Fragment which directs user to the browser.

**Comment by LuGO0** [comment]
> I have added 'Forgot Password?' option in the LogIn Fragment which directs user to the browser.

@Jeetanshu could you please raise an Issue first in JIRA and get it approved by @rishabh-997 then only make a PR.

**Comment by LuGO0** [comment]
https://wiki.openmrs.org/display/docs/Pull+Request+Tips

**Comment by Jeetanshu** [comment]
@LuGO0  Sure.
I'll do it.

**Comment by Jeetanshu** [comment]
@LuGO0 can you please tell me why some of the checks are not successsful??

**Comment by rishabh-997** [comment]
Try to start with beginner issues and go through the PR guidelines. Discuss your issues beforehand or else you will end up wasting your time as you did here. Resetting password is one of the issues with the highest complexity and it's open for 2 years. Go through this link to see how to implement this feature properly.
https://issues.openmrs.org/projects/AC/issues/AC-575

**Comment by Jeetanshu** [comment]
Ok.
Thanks for the suggestion.

**Comment by Jeetanshu** [comment]
@rishabh-997  I'm unable to Log In on https://issues.openmrs.org/projects/AC/issues/AC-575 to discuss on any issue or bug.
It always shows error 'Sorry, your username and password are incorrect - please try again.'
I have tried it many times but still unable to Log In.
Please Help me in this.

**Comment by HerbertYiga** [comment]
> ug.



> @rishabh-997 I'm unable to Log In on https://issues.openmrs.org/projects/AC/issues/AC-575 to discuss on any issue or bug.
> It always shows error 'Sorry, your username and password are incorrect - please try again.'
> I have tried it many times but still unable to Log In.
> Please Help me in this.

what happens when you try to retrieve your account from the login page,this requires your openmrs id or email  to reset your password,check this https://id.openmrs.org/reset

**Pull request closed without merging**
