### PR TITLE
Corrected some grammatical errors in README.md file

### PR DESCRIPTION
**Pull request by Apoorvg2000**
Updated the README.md file by correcting some grammatical and syntactical errors.

### CODE REVIEW

**Comment by rishabh-997** [comment]
Can you attach the ticket id to PR

**Comment by LuGO0** [comment]
@Apoorvg2000 follow our JIRA workflow and make a PR in accordance to that, get the issue ready for work then start working on it !!

**Comment by Bisht13** [comment]
@rishabh-997 @LuGO0 can I work on this? Does this have a ticket or do I have to create one?

**Comment by rishabh-997** [comment]
Closing due to inactivity and failure to meet PR guidelines...

**Pull request closed without merging**
