### PR TITLE
[WIP] AC-405 : Appointment Scheduling

### PR DESCRIPTION
**Pull request by paras7735**
I have completed the Mock Up UI for Appointment Scheduling with Dummy Data.
I am left with connecting the API with the UI.
https://issues.openmrs.org/browse/AC-405

### CODE REVIEW

**Comment by dkayiwa** [comment]
@paras7735 according to this the screenshots should instead be on the JIRA ticket. https://wiki.openmrs.org/display/docs/Pull+Request+Tips

**Comment by paras7735** [comment]
Sure I will upload the screenshots on JIRA.I also shared my initial work on the forum but did not get a reply.So I uploaded them here.I will keep it in mind not to do such mistakes again.

**Comment by dkayiwa** [comment]
@paras7735 do you mind removing the screenshots on github?
As for the forum, can you point me to the link?

**Comment by paras7735** [comment]
Sure, Here is the link to the forum
https://talk.openmrs.org/t/appointment-scheduling-function/13517
I have also put the screenshots on JIRA.
I have also implemented the changes as suggested by @DefCon-007 and am waiting for more suggestions on the UI.

**Comment by dkayiwa** [comment]
@paras7735 did you take a look at the codacy review comments?

**Comment by paras7735** [comment]
Yes I have resolved most of them and the document empty method body check is getting cleared out when I connect the API

**Comment by dkayiwa** [comment]
@paras7735 after you are done addressing all of them, can you commit your changes for review?

**Pull request closed without merging**
