### PR TITLE
AC- 946 fixed language error

### PR DESCRIPTION
**Pull request by K1RA-16**
## Description of what I changed
Fixed the language change error in english to hindi

## Issue I worked on
https://issues.openmrs.org/browse/AC-946

## Checklist: I completed these to help reviewers :)

- [x] My pull request only contains **ONE single commit**

- [ ] I have **added tests** to cover my changes. (If you refactored

- [x] All new and existing **tests passed**.

- [x] My pull request is **based on the latest changes** of the master branch.

### CODE REVIEW

**Comment by K1RA-16** [comment]
@jwnasambu @LuGO0 please review

**Comment by Akshatji800** [comment]
The same changes are done in this [PR](https://github.com/openmrs/openmrs-contrib-android-client/pull/883/files) but @LuGO0 closed the PR informing that the issue is solved without the need of the changes. @LuGO0 can you please confirm the issue exists or not.

**Comment by K1RA-16** [comment]
It does exist 
I forked the latest code and saw that it was still happening

**Comment by Akshatji800** [comment]
If it does exist then I guess the first PR which was made with same changes should be merged. @LuGO0 can you please see to the issue and do whatever seems right to you. This was the first [PR](https://github.com/openmrs/openmrs-contrib-android-client/pull/883) made.

**Comment by K1RA-16** [comment]
> If it does exist then @LuGO0 please have a look at the initial PR I made after reporting the issue as it has the same changes. This was the first [PR](https://github.com/openmrs/openmrs-contrib-android-client/pull/883) made. 
> 
> 

Sure as you find it appropriate.

**Comment by LuGO0** [comment]
I might have made a mistake in closing the PR while checking on my own, will look into it as soon as I get some time I just re-opened the original PR you can close this @K1RA-16

**Pull request closed without merging**
