### PR TITLE
[AC-633] Integrate leak canary to debug version

### PR DESCRIPTION
**Pull request by rishabh-997**
## Description of what I changed
I added debugImplementation of leak canary in the builld.gradlefile.

## Issue I worked on

JIRA Issue: https://issues.openmrs.org/browse/AC-633

## Checklist: I completed these to help reviewers :)

- [x] My pull request only contains **ONE single commit**
(the number above, next to the 'Commits' tab is 1).

- [ ] I have **added tests** to cover my changes. (If you refactored
existing code that was well tested you do not have to add tests)

- [x] All new and existing **tests passed**.

- [x] My pull request is **based on the latest changes** of the master branch.

### CODE REVIEW

**Comment by rishabh-997** [comment]
@vansha10 @f4ww4z  please have a look.

**Comment by vansha10** [comment]
@rishabh-997 Please go through the [Pull Request Guidelines](https://wiki.openmrs.org/plugins/servlet/mobile?contentId=60785449#content/view/60785449). 
Do not start working on issues before they have been marked 'Ready For Work'.

**Comment by rishabh-997** [comment]
> @rishabh-997 Please go through the [Pull Request Guidelines](https://wiki.openmrs.org/plugins/servlet/mobile?contentId=60785449#content/view/60785449).
> Do not start working on issues before they have been marked 'Ready For Work'.

I didn't know this, will take care next time...

**Comment by rishabh-997** [comment]
> Looks good @rishabh-997 , thanks for the PR. Please follow the PR tips next time, see my comments in the JIRA issue page.

I have claimed the task, you can merge now

**Pull request merged**
