### PR TITLE
AC-302 Lint adjustment - Performance

### PR DESCRIPTION
**Pull request by hao555sky**

### CODE REVIEW

**Comment by jsroyal** [comment]
Hey! @hao555sky Are you working on it?
If not please close PR.

**Comment by hao555sky** [comment]
Hi, @jsroyal 
I have fixed the [issue](https://issues.openmrs.org/browse/AC-302?jql=project%20%3D%20AC%20AND%20resolution%20%3D%20Unresolved%20AND%20status%20%3D%20%22Ready%20for%20Work%22%20ORDER%20BY%20priority%20DESC), why do I close PR?
Can you give me a reason? Thank you.

**Comment by hao555sky** [comment]
Hi, @AvijitGhosh82 

I have fixed the [issue](https://issues.openmrs.org/browse/AC-302?jql=project%20%3D%20AC%20AND%20resolution%20%3D%20Unresolved%20ORDER%20BY%20priority%20DESC) and created pull request for 2 days.

Can you review it and give me some comments if I did something wrong.

Thank you. Have a good day.

**Comment by jsroyal** [comment]
Oh, Sorry!  @hao555sky. I  thought you mistakenly open pull request as I saw in the pull request everything was deleted.
Sorry, I still uncomfortable track issue in Jira.
Can you please write an overview of this PR in the description.

Can you help me how to track issue and created ticket?
I submitted  Jira help form but still did not get ID.
So how should I do?

**Comment by hao555sky** [comment]
Hi, @jsroyal 
You should wait some time because last two days are weekends. 
And you can visit the [site](https://issues.openmrs.org) to see issues. 
You can talk to me through other methods. Here is improper.

**Comment by AvijitGhosh82** [comment]
@hao555sky , Are you sure completely deleting the files is the right way? I'm not sure if all of them are meant to be discarded. 
There is another PR for AC-302 where the author has done line by line replacement.

**Comment by hao555sky** [comment]
@AvijitGhosh82 
I will check and open a new pull request if need.
Sorry.

**Pull request closed without merging**
