### PR TITLE
AC-234 - Followup commit

### PR DESCRIPTION
**Pull request by tmarzeion**
I've added missing encounter type error handling and improved layout look

### CODE REVIEW

**Comment by shivtej1505** [comment]
@tmarzeion , I'm facing some issue while testing this PR. I've mentioned it on Issue Page, could you please check?

**Comment by tmarzeion** [comment]
@shivtej1505 Check if NullPointer is still happening :)

**Comment by shivtej1505** [comment]
@rkorytkowski , @tmarzeion  I think we can merge it now.

**Comment by AdamGrzybkowski** [comment]
@tmarzeion  can you squash this to one commit ?

**Comment by tmarzeion** [comment]
@AdamGrzybkowski squashed

**Pull request merged**
