### PR TITLE
AC-539 Added Outlined Box in Patient Info Form

### PR DESCRIPTION
**Pull request by deepak140596**
AC-539
Added Outlined Box in Patient Info Form

## Description of what I changed
Changed Margin of views in the form to be consistent throughout 
Added Styled OutlinedBox for EditTexts in the form 

## Issue I worked on

JIRA Issue: https://issues.openmrs.org/browse/AC-539

## Checklist: I completed these to help reviewers :)

- [x ] My pull request only contains **ONE single commit**
(the number above, next to the 'Commits' tab is 1).

- [ ] I have **added tests** to cover my changes. (If you refactored
existing code that was well tested you do not have to add tests)

- [ ] All new and existing **tests passed**.

- [x ] My pull request is **based on the latest changes** of the master branch.

screenshot_20190307-124250 1

### CODE REVIEW

**Comment by deepak140596** [comment]
Hi,
Check this PR for the improved UI changes in the form of patient_info.

**Comment by ODORA0** [comment]
Could you add the ticket ID as required by https://wiki.openmrs.org/display/docs/Pull+Request+Tips?

**Comment by deepak140596** [comment]
Sorry for not providing the ticket ID. 
I am new to the community. As soon as I get accepted to the community, I will open a JIRA ticket and add the same here.

**Comment by deepak140596** [comment]
Will create a new PR with a single commit

**Pull request closed without merging**
